import type { Handle } from '@sveltejs/kit';
import { FetchHttpClient } from '@effect/platform';
import { Layer } from 'effect';

import { AmProxyLive } from '$server/services/am-proxy.live';
import { AppConfigService } from '$server/services/app-config';
import { OidcDiscoveryService } from '$server/services/oidc-discovery';
import { RateLimiterLive } from '$server/services/rate-limiter';
import { initializeAppRuntime } from '$server/run';

/**
 * FetchHttpClient with redirect: 'manual' — the BFF proxies redirect responses
 * rather than following them (needed for OAuth authorize flow).
 */
const HttpClientLive = Layer.provide(
  FetchHttpClient.layer,
  Layer.succeed(FetchHttpClient.RequestInit, {
    redirect: 'manual',
  } satisfies globalThis.RequestInit),
);

/**
 * Layer composition — no session store needed (stateless cookie architecture):
 * 1. BaseLayer: AppConfigService.Default + HttpClientLive (no deps)
 * 2. WithDiscovery: OidcDiscoveryService.Default needs HttpClient (AppConfig auto-provided via dependencies)
 * 3. AmProxyLive needs AppConfig + HttpClient + OidcDiscoveryService
 *
 * Signal handling (SIGTERM/SIGINT) is managed by ShutdownSignal service,
 * merged into the runtime by initializeAppRuntime via acquireRelease.
 */
const BaseLayer = Layer.merge(AppConfigService.Default, HttpClientLive);
const WithDiscovery = Layer.provideMerge(OidcDiscoveryService.Default, BaseLayer);
const WithAmProxy = Layer.provideMerge(AmProxyLive, WithDiscovery);
const AppLayerLive = Layer.provideMerge(RateLimiterLive, WithAmProxy);

initializeAppRuntime(AppLayerLive);

/**
 * Additional security headers (beyond CSP which SvelteKit handles via svelte.config.js).
 */
const SECURITY_HEADERS: Record<string, string> = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'X-DNS-Prefetch-Control': 'off',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  // HSTS only applies when serving over HTTPS — sending it over HTTP is a no-op
  // and confuses some proxies/load balancers.
  ...(process.env.ORIGIN?.startsWith('https://')
    ? { 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains' }
    : {}),
};

/**
 * SvelteKit's handle hook — sets security headers and manages CSP per-route.
 *
 * CSP is generated by SvelteKit (svelte.config.js) with auto-nonces for inline
 * hydration scripts. This hook applies per-route overrides:
 * - /e2e routes: CSP + security headers removed (widget makes direct AM requests)
 * - /callback: frame-ancestors relaxed to 'self' (SDK uses hidden iframe for OAuth)
 * - All other routes: full restrictive headers
 *
 * CSRF protection is handled by SvelteKit's built-in `csrf.checkOrigin`.
 */
export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  const path = event.url.pathname;

  // E2E routes serve the client-side widget which makes direct cross-origin
  // requests to AM, loads external scripts (reCAPTCHA), and uses iframes for
  // the OAuth authorize flow. These pages are never shipped to production —
  // they exist solely for testing, so strip restrictive headers unconditionally.
  if (path.startsWith('/e2e')) {
    response.headers.delete('content-security-policy');
    return response;
  }

  for (const [header, value] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(header, value);
  }

  // The SDK loads /callback in a hidden iframe for OAuth code exchange.
  // Relax frame restrictions so the iframe redirect can complete.
  if (path === '/callback') {
    const csp = response.headers.get('content-security-policy');
    if (csp) {
      response.headers.set(
        'content-security-policy',
        csp.replace("frame-ancestors 'none'", "frame-ancestors 'self'"),
      );
    }
    response.headers.set('X-Frame-Options', 'SAMEORIGIN');
  }

  return response;
};
