/**
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 **/

import { oidc } from '@forgerock/oidc-client';
import { writable } from 'svelte/store';
import { z } from 'zod';

import type { OidcClient } from '@forgerock/oidc-client/types';
import type { Readable } from 'svelte/store';

/**
 * Configure the OIDC Client.
 */
export const oidcClientConfigSchema = z
  .object({
    clientId: z.string(),
    redirectUri: z.string().url({
      message: '`redirectUri` must be a full URL (this is generated by the Zod library).',
    }),
    scope: z.string().default('openid'),
    serverConfig: z
      .object({
        wellknown: z
          .string({
            error: (issue) =>
              issue.input === undefined
                ? 'Setting the `serverConfig.wellknown` is required (this is generated by the Zod library).'
                : '`serverConfig.wellknown` must be a URL string (this is generated by the Zod library).',
          })
          .url({
            message:
              '`serverConfig.wellknown` must be a full URL (this is generated by the Zod library).',
          }),
      })
      .strict(),
  })
  .strict();

export type OidcClientConfig = z.infer<typeof oidcClientConfigSchema>;
export type OidcClientStore = Readable<OidcClient | null>;

/**
 * @function createOidcClientStore
 *
 * Wraps the `oidc()` factory in a Svelte store. Starts as `null`, transitions to
 * the resolved `OidcClient` when the wellknown fetch settles.
 * Inject the returned store into OAuth and User stores so both share the same
 * client instance without module-level state.
 *
 * @param {OidcClientConfig} config — OIDC client configuration (validated by Zod).
 * @returns {OidcClientStore}
 */
export function createOidcClientStore(config: OidcClientConfig): OidcClientStore {
  const parsedConfig = oidcClientConfigSchema.parse(config);
  const { subscribe, set } = writable<OidcClient | null>(null);

  oidc({ config: parsedConfig })
    .then((client) => {
      set(client);
    })
    .catch((err: unknown) => {
      set({ error: err instanceof Error ? err.message : String(err) } as unknown as OidcClient);
    });

  return { subscribe };
}
