import { type Step, CallbackType } from '@forgerock/javascript-sdk';

export const deviceProfileAloneData: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkRldmljZVByb2ZpbGUiLCJvdGsiOiJsbW1nZGg3bWQxOWowNWQ3bGltMjY2dmNkayIsImF1dGhJbmRleFR5cGUiOiJzZXJ2aWNlIiwicmVhbG0iOiIvYWxwaGEiLCJzZXNzaW9uSWQiOiIqQUFKVFNRQUNNRElBQkhSNWNHVUFDRXBYVkY5QlZWUklBQUpUTVFBQ01ERS4qZXlKMGVYQWlPaUpLVjFRaUxDSmpkSGtpT2lKS1YxUWlMQ0poYkdjaU9pSklVekkxTmlKOS5aWGxLTUdWWVFXbFBhVXBMVmpGUmFVeERTbXhpYlUxcFQybEtRazFVU1RSUk1FcEVURlZvVkUxcVZUSkphWGRwV1ZkNGJrbHFiMmxhUjJ4NVNXNHdMaTVYWTA1aU9ITmxVekIxUmtadFNFTXdXa2RLU0haM0xrSk5lRlZsUVVGclpWVkxiVlY1WWw5VFgyUm1kak5qY1U1d1VXWlVRV0pOU2kxak4xZFpTMUUwYm1GU1MwOHpiMlV5V25kU1JXWlRMVTFDVFhORVRVcGxNMUkzYWxoRE1tWmhRbGhHY3psdVdrRTVZbEp3WDBGeVVWa3lPV2hNUW1oclVURnZXVkIwYjFWdmFXSlNRWEkxZVVJMGRUbHlXbkZIVFVrMWJrVlRPV1poY3pSMFNYVkNWVXBrUVZCd2RFczRNV1pXVFdaU1dWVjVVVVowYW10NmQxRm9NRnAwVVMxTGVYaE5Rakp1Y0ZJNGJVbHNlbVpUVnpKWFpFUm9WMDFCZURWeFpYRkNTRlUyVTJwdlgyMHlkRVpLZG1OT2VVOWxlbVJNTTNFeFZVZFhTR1JpUWtoR1ZXMWpNamRPZUZaeldVeHZRa2x3TkZWVWJrZEZaek5MV0Zoc05qVnFWMjB3Y1dSeFNsQnlkVjloZG01TGJtdzRlVTVOU0ZGUVpreGpPVkF3V2tGZlJVSnBXR2xTVUVZeGFGUmZjRFpEZDNBMk5tZFhSVTlQV1V0R1NUSTBSVGRUVUdnM1NWY3lZV2QzV1ZOaFJXWjFSVWRmTTNFd1EzUkdSMk5xYW1nNVpVaGFVUzF1ZVRWUFJUVm9SVXd6YjNWcFUySTBaa2xwVGxjMFRtZzBaemwzYlVOR1QxbG9ZMlZKYURKdU5rUkpaRWMzVTJOQ2NHdE9hMWh6ZG1salFsTmhXRUUyZFdFeVJuSm1jVVEzY1RCUVpVMTFTa2R3WkVVNWMycG9iRmR0YkV4MVp5MXJXa3czYkhWMGJscDNZVU42YmtzNWFVcG5lV3RWVm1OMVJHWm5XRXBxZFdodGRXWnNkVFZ4U0VWak9GZFplSGd5WmpSek5pMVJOMGhoVkdsRUxVNTJaMFpZWnpaVlFqZGFWMmw0WlRsdFRVNUdaSFEzU1RjMVJXVkxOVzU2UW1sSUxUVlNObEZwV2sxTU5rdGZXalV0VVhOU1NtcFZZeTFhYTFwdFlUSkNVR1ZaVVhaVlpsTjFNMDFKTjJwcE1XUm5RbG95TVdwd2FHUlFVbU15WTNOUlozbzNYMkZNVlhGRlN6WjVObmRmWTJaSE5UaFViSFZoYTBOYVduTm9OV1pUVmtSMWVHRk1UMnRGYkRsUmRIUXlhMk5QZWxoRFpFRkxUV0YxY1hoS1NtVlFZUzFMVEd4QlZtTk1UbUozV0c1R1VHOXBXVGhzYjI1V00wbGtZamxYTkdKQ1QzSTJVa05uUlVKRlJUVkJRemwzU0dNNFdHZG1URXRHVVVkdWJEQlpNVU5rU2t0NVlTMXRiMDVUZERGbWFWYzBaMVpwY1hKelVtbzNVVmR4TjFwRU4zcHlVVGRIUlc5a09UZzBUREZEYVdnek1teHBNMng1T0RsV1VVMXFhbEJaTkVJekxWVkVkR1pPVDBsR1gwd3hUMDVEVFVSRGNtZEtTMWxEY1ZFdGQzWlJTSFI2YVc5M09WcHdNVlJZTWxsQ1FtNW9hRXBFVm5kTk1GbEtNMWhFWVVWVFNFMDVVMnRwTFdFME1HTmtZbVF0UW1ab2VYVnhRV2htVVdkbWF6VnlZVVpDYW1SMGNVbHhVRWcwVlRadmR6bFdSMlZ6VFdKcFJ6WkVVRkZYWmxGS1FsUnJVRWRrYUhGSFlYUmhabEkyZUhoV1Ztb3libFpQUzFSYVFUSnNZUzFDUkU5ZlgydHJhVE5PYUZGcmJFWmZOeTFaYVcxQlkyeEhPSFI1UjFSZmVGTndiRmg2V0c4M1pUZEthR2R6YVhBeGJFOXBkbU5ITW5aMk5tbG5PWFIxWXpONFJVbExWa2c1ZHpWelpVSjJSbEJRWm5GWGNtNHdXVmRrZVhkSVpUUnNkWHBwUTA5UVdGZzRSa2huVEMxU2JWQkZaV0Z6WTIxT2NEWmthRmhaTWtKTlkyTTJlVEJEWTFKSGRXWkNWVGRXVTNFdFgwdE1aV2QxYUdnMmVrcHZTVnBpUVdSWVVsSlpSMmRETWtOWFV6WkljSEZHZVhWc1RYUnBUWGsyVVZkc1IxbElXR2xIUkVWSWVVeENiM051YUhkdFFUWjJSekJVTlhCR1IwMW9NbkJIUlhZeWFqbGlWRXBZTlZoeFowSnNSR0UwUkdaWmFtdEVVa1pYVERGVFNFTkhVRTh5WlhsZlRtUjFNMmMwZUcxNlJqWllaSFJyTTFkMU4ybE9NREpqWmtkMlFrUk1Oa3BJY1U5MmMwdExPVUZvUlZCblZXaGxSVzFXWVMwME9VOXVWVEp3VVd4d1JTMXBlVTlpV2s1bFdEVnhOM3BYUTIxS1pHZEJUVUZQWTBWVlNubFFTalJCY2pGb1pHSnJRVlZyYTFCNFgweDFSRVoxY2tZM2JXUlpWa3RpWjA1RGFXbEthblpaUkY5alJ6VlNZa28xZWpKMWFtbGZWSFZqWVRaSWVGaHJWRzVLWVRkcGMyRlBNRXhyU25nNFduRklRa2xIZG1kRllWcDFNM054TVVKaWVGRk5NVVptUjFvM0xXeHplWEpPYld4NlZYTXRURTFXYUhacVVteHBZVGhZTlhob01tMXVOMEpCWHpka1dsUjFVVzFLVm0xUmJIWmxUM0pTUWpKcWJuQTJPREExT0ZKMFgxQTBlVXBRWWpjMlIySXRZbU13T0V0QmJHazFTbTVXUWsxRlFrbDJRV1JMYUhScGJHUktXRTFQTURrM1VIUm5halZzT0RSMmNIVnhlR001UmxGeE9XUnFVMFpzZDJkamVtY3hjblpSZDFkbGJ6ZFlibU5WWXpKU1RqRnZPR3hGVVhwVmQzaENhVXRIVVRad1VqTjRibGx5TTFScFlVZHlNbDlPTFhoNFdHOVlPR05HWmpsT1dHWmlVM3B1WlVObE5WZGFiVXR0TW1kdlRVeHBjMlp6TlVaamFFWXRORGhJV1VaQ2RWRXlkM0o1VUZWMlJFdEVSR2hCTWtwVGVHTmpVMjlDUkhOeFYxUTFSVU5IVlRaVlZWZERWVmhDY0RsdWRqRnFWM1J1VkhNdGJYUXliakJqUXpsSk5sbFlTRGhMUVd4WmEwUlpTMmx1ZW1WclJ6RnBMVVZpVm1GT04wMHhRa1ppZUY5VFR6QnVha281VGpCeVJIUkdiV1JFU21WV1FrRlZNVGhmY1ZGTFIwdEhURVJNYWtsM1oyMVlaVEZIZGtGSkxUaHJlbTFqVmw5MlpIVjBiRUpmZFZvM2VucGZORUpMYms5MVNGOVFUemQyUnpZMFNrdFhWbGRQWjFoeVduVTFSazR0ZVRsSWIxUm1ZbEpUY0ZSeUxXMU9URzFmVGs0MFFrMW9hRFJOTUY4NFZIZHFTVzlhYVVkcmFYWlhSWFEwUTIxT1N6aGtXSFZRUzJ4bk4yWlNNVmxFVTNvNWRIQm1RMUZ4UkhBNU5YVnJVRWRMWlY5M09WUjFiVFpVYjB4cE1GcE1heTAxWVdST1VtZHRWRUpYUkhwUWVHbE1jalZQTVRkM2NuZE9aVlYxYW5OMllVMVhVbXhKZVRaWlFVZHpSMkpFWTFGUVJ6WkZkMlo1UmpWRVZHUTNhbFZQVjFweWJuZFlja3BHYVhoNVJsaGZMWFUyUmkxWU1XNXhVbFp1Y25wVFJESnJXVXBvTWtaSmFERlRlbTFSTWs4d1ZFVmFRbVpwVEhBd09WQnVTazlRYWt0Mk9HaDNZbGRrY1RWTWRUbGlUemQwVGt4dGFGcFRUMHhuVkVoS1pHOUhWRzFKVW1oeVQzQXlUSEJLZEVwaVFXaHpja1U0ZEVGbU4zWTBkMHAwYUZWRVgySmZhMTlNVTJ4dVQxWk9XR05QTlhKb04wd3lVV3RTTFhCRlEzbzRaakJFZGxSTlZtbHdiMWxYTlZsTVVHUXRNbk5JTlZkWFNVRjFTMDFzYjNablkycFBOblE0TmxSVFJtSlRNRWRtZVhGWlVVMW1PRTR0TTJOVU5UTndhVzlZWkdadlNqbEdkSFEyVTBkTE9YWjNXVTFITTFrM01UVm1ZV052VDE5d2JGQTBiVjlGTTBsa2FrdEthRjh4T1cwNE9WSldUbXREVjB3MFpHVXhUbXh6YjNSVlJGRXhPVmx6YXkxVlNubDBjMFZzVkd3eGNVZHFVak15VVV0dk5VOXNYMmhQZVZWRlZUVTFkRUU1YUhWNk1ERkhhREoxV0dOcFFrbDNWVTFWYzFKSGNIQnpXVmxqTjBwbVExOWpielU0UkVaaFdTMDFSVUZ2YjBselVuUjNTVkZqYnpKV2NFRTFXWEJqTWpWdVZrczNjVmxGTmxwMWNYQk1iRXhpY0RCblZHcEROMVIwVUZWblNHVnRSMFpzYkhWcGRsRnpOWEJpV1ZwWFJWTnpkSGxwTTIxS1RrSnRPRGxNTWs1aU1VNUVOemhRVkVSNVJtZENRMEl0U1U5Sk5qaFhVbGxNYWtWSFIxUlZkWEEzUVdsbmQzRlJNVTV2VWkxT1MwaGpUMHgzTkVKYU5XbEVUSEl5TXpBd05GSmhNMll4VTIxNU1GQllOMWh4UmkxbU0zaFZlalIwVFZBeE5UZEtTRmx0WVVwcFFuYzROVmhMVjBSaGRXaFFMVnBvVFVneFlqWXpWa1UyU25rMldVNXRRMWRYTldZNVRIQmZNMWhGY2xoSVNEWnZWWGt6UTJwbFZIbHVlRlUyVUhacVEwNVpWazgyUzJKbmNEZFhWVFpTY2pSeVJURXdSbWczVVMxaWNrSmFVSGhDWTJSNlNtOXRSVEpDZGpFd1ZIQjJPV1J3TkUxdE5WbDVhVVF6UTBKd2FIcFdaVjh6Y0VWa1MwWlJSVTVvWTA1Wk1HdEVlR1pHT0dodWVucEhlbEJKT1ZkWFREYzRjV3hxYjI4MFNtTnRNRUpRVVhCV1dWbzBTVmhqWmt0WFJsWnNXa3R6TjJGVk5GbGtNa0V6UjJwck5tTk9UR055ZWt0dVVraHdUa2hwTldKc2JqWlBXbWcxTTJOcFJXNTRNVXRSTUhSUFZXZG9ibEpUTjI5dU9FTmtUbFJHWkRkUVIyUTFNV0pGZUhKVVdrZ3lZbmRWTldsd2RIY3dibXhIVUZBNVIxZzRTMk5pVW10eVIwUXlURUZGVVZOdWFtbHRkM1pYVlVkb1lVVlZOMVkxZEc1ck9HZDRTMk5rWTFOcFMySXpaelZhUlRRMVNFVlNMV2h0TlhaU2VWbHRRa1kxVmxSeU1uWkNVbFEwYlc1Nk9WSXdTblJEV2sxcWFrWlNhM1ozV0hZMFFXUkdORFpIYjJOSVlteHpZa1p2VW05VE5UZDFheTFCYzNFNFpHNUNSelUwWjFKaWRESk5Ta2xMVldkRGRFVm9ZbU4yWmkxSFVuY3hWa1kwTmtGUGNGZEJTQzFJTm05UE0weDZRMDlZVVhKSVRWQkxWakpVVlZSSldrd3lORUV4T1RWbE5IZGlhSFpQVm5sSlVuRlBPVlp1VW1WNlVYUlVjbVZMU0ROaVN6RlFYM0JWWlVFNFkxRXdhSEZvUVhKMFdYaHRSMlJyZEdGMVZIbG1OMWhsYVhGT2FXSjVjMFZJTFZsdWVGVkZia0ZtUjFsa2JESk1MV2Q2WW1WRmJ6WXhiV1U1WkcxUmVFUnRReloxZG5OTlZHbEZNMXBMVUZkemMzazNlbTFYU1VkbGJtVXlVMjVMUzNsNmMzWXdaRlZMUzA1TGMwdG5OMGsxZDFSb2RrbFdSVFI2TFZCdlowOVpjRkZWU1ZkMmVGQnhTblE0TFZoNFgyZ3RhbTlJTWtSMWNqUktiMEYxYXkxdlpHcG1PRXhqVG5OeGRHY3VhSHBoTlVkb2VUSmFOMFIzUW01SVNYbEJTMXAzWncuQ3JMWFhqUDZTbERFVHdTU2ozSXZ6bDVsSGdzazVTZHpmby14WlJCQzVITSIsImV4cCI6MTY4Mzc1NzU2NCwiaWF0IjoxNjgzNzU3MjY0fQ.CridMM7bwY0S0xESITD47gmmqnS2IUHv_XXedo4mhEY',
  callbacks: [
    {
      type: CallbackType.DeviceProfileCallback,
      output: [
        {
          name: 'metadata',
          value: true,
        },
        {
          name: 'location',
          value: true,
        },
        {
          name: 'message',
          value: 'my message',
        },
      ],
      input: [
        {
          name: 'IDToken3',
          value: '',
        },
      ],
      _id: 2,
    },
  ],
  stage: 'DeviceProfileLogin',
};
export const deviceProfileComposition: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkRldmljZVByb2ZpbGUiLCJvdGsiOiJsbW1nZGg3bWQxOWowNWQ3bGltMjY2dmNkayIsImF1dGhJbmRleFR5cGUiOiJzZXJ2aWNlIiwicmVhbG0iOiIvYWxwaGEiLCJzZXNzaW9uSWQiOiIqQUFKVFNRQUNNRElBQkhSNWNHVUFDRXBYVkY5QlZWUklBQUpUTVFBQ01ERS4qZXlKMGVYQWlPaUpLVjFRaUxDSmpkSGtpT2lKS1YxUWlMQ0poYkdjaU9pSklVekkxTmlKOS5aWGxLTUdWWVFXbFBhVXBMVmpGUmFVeERTbXhpYlUxcFQybEtRazFVU1RSUk1FcEVURlZvVkUxcVZUSkphWGRwV1ZkNGJrbHFiMmxhUjJ4NVNXNHdMaTVYWTA1aU9ITmxVekIxUmtadFNFTXdXa2RLU0haM0xrSk5lRlZsUVVGclpWVkxiVlY1WWw5VFgyUm1kak5qY1U1d1VXWlVRV0pOU2kxak4xZFpTMUUwYm1GU1MwOHpiMlV5V25kU1JXWlRMVTFDVFhORVRVcGxNMUkzYWxoRE1tWmhRbGhHY3psdVdrRTVZbEp3WDBGeVVWa3lPV2hNUW1oclVURnZXVkIwYjFWdmFXSlNRWEkxZVVJMGRUbHlXbkZIVFVrMWJrVlRPV1poY3pSMFNYVkNWVXBrUVZCd2RFczRNV1pXVFdaU1dWVjVVVVowYW10NmQxRm9NRnAwVVMxTGVYaE5Rakp1Y0ZJNGJVbHNlbVpUVnpKWFpFUm9WMDFCZURWeFpYRkNTRlUyVTJwdlgyMHlkRVpLZG1OT2VVOWxlbVJNTTNFeFZVZFhTR1JpUWtoR1ZXMWpNamRPZUZaeldVeHZRa2x3TkZWVWJrZEZaek5MV0Zoc05qVnFWMjB3Y1dSeFNsQnlkVjloZG01TGJtdzRlVTVOU0ZGUVpreGpPVkF3V2tGZlJVSnBXR2xTVUVZeGFGUmZjRFpEZDNBMk5tZFhSVTlQV1V0R1NUSTBSVGRUVUdnM1NWY3lZV2QzV1ZOaFJXWjFSVWRmTTNFd1EzUkdSMk5xYW1nNVpVaGFVUzF1ZVRWUFJUVm9SVXd6YjNWcFUySTBaa2xwVGxjMFRtZzBaemwzYlVOR1QxbG9ZMlZKYURKdU5rUkpaRWMzVTJOQ2NHdE9hMWh6ZG1salFsTmhXRUUyZFdFeVJuSm1jVVEzY1RCUVpVMTFTa2R3WkVVNWMycG9iRmR0YkV4MVp5MXJXa3czYkhWMGJscDNZVU42YmtzNWFVcG5lV3RWVm1OMVJHWm5XRXBxZFdodGRXWnNkVFZ4U0VWak9GZFplSGd5WmpSek5pMVJOMGhoVkdsRUxVNTJaMFpZWnpaVlFqZGFWMmw0WlRsdFRVNUdaSFEzU1RjMVJXVkxOVzU2UW1sSUxUVlNObEZwV2sxTU5rdGZXalV0VVhOU1NtcFZZeTFhYTFwdFlUSkNVR1ZaVVhaVlpsTjFNMDFKTjJwcE1XUm5RbG95TVdwd2FHUlFVbU15WTNOUlozbzNYMkZNVlhGRlN6WjVObmRmWTJaSE5UaFViSFZoYTBOYVduTm9OV1pUVmtSMWVHRk1UMnRGYkRsUmRIUXlhMk5QZWxoRFpFRkxUV0YxY1hoS1NtVlFZUzFMVEd4QlZtTk1UbUozV0c1R1VHOXBXVGhzYjI1V00wbGtZamxYTkdKQ1QzSTJVa05uUlVKRlJUVkJRemwzU0dNNFdHZG1URXRHVVVkdWJEQlpNVU5rU2t0NVlTMXRiMDVUZERGbWFWYzBaMVpwY1hKelVtbzNVVmR4TjFwRU4zcHlVVGRIUlc5a09UZzBUREZEYVdnek1teHBNMng1T0RsV1VVMXFhbEJaTkVJekxWVkVkR1pPVDBsR1gwd3hUMDVEVFVSRGNtZEtTMWxEY1ZFdGQzWlJTSFI2YVc5M09WcHdNVlJZTWxsQ1FtNW9hRXBFVm5kTk1GbEtNMWhFWVVWVFNFMDVVMnRwTFdFME1HTmtZbVF0UW1ab2VYVnhRV2htVVdkbWF6VnlZVVpDYW1SMGNVbHhVRWcwVlRadmR6bFdSMlZ6VFdKcFJ6WkVVRkZYWmxGS1FsUnJVRWRrYUhGSFlYUmhabEkyZUhoV1Ztb3libFpQUzFSYVFUSnNZUzFDUkU5ZlgydHJhVE5PYUZGcmJFWmZOeTFaYVcxQlkyeEhPSFI1UjFSZmVGTndiRmg2V0c4M1pUZEthR2R6YVhBeGJFOXBkbU5ITW5aMk5tbG5PWFIxWXpONFJVbExWa2c1ZHpWelpVSjJSbEJRWm5GWGNtNHdXVmRrZVhkSVpUUnNkWHBwUTA5UVdGZzRSa2huVEMxU2JWQkZaV0Z6WTIxT2NEWmthRmhaTWtKTlkyTTJlVEJEWTFKSGRXWkNWVGRXVTNFdFgwdE1aV2QxYUdnMmVrcHZTVnBpUVdSWVVsSlpSMmRETWtOWFV6WkljSEZHZVhWc1RYUnBUWGsyVVZkc1IxbElXR2xIUkVWSWVVeENiM051YUhkdFFUWjJSekJVTlhCR1IwMW9NbkJIUlhZeWFqbGlWRXBZTlZoeFowSnNSR0UwUkdaWmFtdEVVa1pYVERGVFNFTkhVRTh5WlhsZlRtUjFNMmMwZUcxNlJqWllaSFJyTTFkMU4ybE9NREpqWmtkMlFrUk1Oa3BJY1U5MmMwdExPVUZvUlZCblZXaGxSVzFXWVMwME9VOXVWVEp3VVd4d1JTMXBlVTlpV2s1bFdEVnhOM3BYUTIxS1pHZEJUVUZQWTBWVlNubFFTalJCY2pGb1pHSnJRVlZyYTFCNFgweDFSRVoxY2tZM2JXUlpWa3RpWjA1RGFXbEthblpaUkY5alJ6VlNZa28xZWpKMWFtbGZWSFZqWVRaSWVGaHJWRzVLWVRkcGMyRlBNRXhyU25nNFduRklRa2xIZG1kRllWcDFNM054TVVKaWVGRk5NVVptUjFvM0xXeHplWEpPYld4NlZYTXRURTFXYUhacVVteHBZVGhZTlhob01tMXVOMEpCWHpka1dsUjFVVzFLVm0xUmJIWmxUM0pTUWpKcWJuQTJPREExT0ZKMFgxQTBlVXBRWWpjMlIySXRZbU13T0V0QmJHazFTbTVXUWsxRlFrbDJRV1JMYUhScGJHUktXRTFQTURrM1VIUm5halZzT0RSMmNIVnhlR001UmxGeE9XUnFVMFpzZDJkamVtY3hjblpSZDFkbGJ6ZFlibU5WWXpKU1RqRnZPR3hGVVhwVmQzaENhVXRIVVRad1VqTjRibGx5TTFScFlVZHlNbDlPTFhoNFdHOVlPR05HWmpsT1dHWmlVM3B1WlVObE5WZGFiVXR0TW1kdlRVeHBjMlp6TlVaamFFWXRORGhJV1VaQ2RWRXlkM0o1VUZWMlJFdEVSR2hCTWtwVGVHTmpVMjlDUkhOeFYxUTFSVU5IVlRaVlZWZERWVmhDY0RsdWRqRnFWM1J1VkhNdGJYUXliakJqUXpsSk5sbFlTRGhMUVd4WmEwUlpTMmx1ZW1WclJ6RnBMVVZpVm1GT04wMHhRa1ppZUY5VFR6QnVha281VGpCeVJIUkdiV1JFU21WV1FrRlZNVGhmY1ZGTFIwdEhURVJNYWtsM1oyMVlaVEZIZGtGSkxUaHJlbTFqVmw5MlpIVjBiRUpmZFZvM2VucGZORUpMYms5MVNGOVFUemQyUnpZMFNrdFhWbGRQWjFoeVduVTFSazR0ZVRsSWIxUm1ZbEpUY0ZSeUxXMU9URzFmVGs0MFFrMW9hRFJOTUY4NFZIZHFTVzlhYVVkcmFYWlhSWFEwUTIxT1N6aGtXSFZRUzJ4bk4yWlNNVmxFVTNvNWRIQm1RMUZ4UkhBNU5YVnJVRWRMWlY5M09WUjFiVFpVYjB4cE1GcE1heTAxWVdST1VtZHRWRUpYUkhwUWVHbE1jalZQTVRkM2NuZE9aVlYxYW5OMllVMVhVbXhKZVRaWlFVZHpSMkpFWTFGUVJ6WkZkMlo1UmpWRVZHUTNhbFZQVjFweWJuZFlja3BHYVhoNVJsaGZMWFUyUmkxWU1XNXhVbFp1Y25wVFJESnJXVXBvTWtaSmFERlRlbTFSTWs4d1ZFVmFRbVpwVEhBd09WQnVTazlRYWt0Mk9HaDNZbGRrY1RWTWRUbGlUemQwVGt4dGFGcFRUMHhuVkVoS1pHOUhWRzFKVW1oeVQzQXlUSEJLZEVwaVFXaHpja1U0ZEVGbU4zWTBkMHAwYUZWRVgySmZhMTlNVTJ4dVQxWk9XR05QTlhKb04wd3lVV3RTTFhCRlEzbzRaakJFZGxSTlZtbHdiMWxYTlZsTVVHUXRNbk5JTlZkWFNVRjFTMDFzYjNablkycFBOblE0TmxSVFJtSlRNRWRtZVhGWlVVMW1PRTR0TTJOVU5UTndhVzlZWkdadlNqbEdkSFEyVTBkTE9YWjNXVTFITTFrM01UVm1ZV052VDE5d2JGQTBiVjlGTTBsa2FrdEthRjh4T1cwNE9WSldUbXREVjB3MFpHVXhUbXh6YjNSVlJGRXhPVmx6YXkxVlNubDBjMFZzVkd3eGNVZHFVak15VVV0dk5VOXNYMmhQZVZWRlZUVTFkRUU1YUhWNk1ERkhhREoxV0dOcFFrbDNWVTFWYzFKSGNIQnpXVmxqTjBwbVExOWpielU0UkVaaFdTMDFSVUZ2YjBselVuUjNTVkZqYnpKV2NFRTFXWEJqTWpWdVZrczNjVmxGTmxwMWNYQk1iRXhpY0RCblZHcEROMVIwVUZWblNHVnRSMFpzYkhWcGRsRnpOWEJpV1ZwWFJWTnpkSGxwTTIxS1RrSnRPRGxNTWs1aU1VNUVOemhRVkVSNVJtZENRMEl0U1U5Sk5qaFhVbGxNYWtWSFIxUlZkWEEzUVdsbmQzRlJNVTV2VWkxT1MwaGpUMHgzTkVKYU5XbEVUSEl5TXpBd05GSmhNMll4VTIxNU1GQllOMWh4UmkxbU0zaFZlalIwVFZBeE5UZEtTRmx0WVVwcFFuYzROVmhMVjBSaGRXaFFMVnBvVFVneFlqWXpWa1UyU25rMldVNXRRMWRYTldZNVRIQmZNMWhGY2xoSVNEWnZWWGt6UTJwbFZIbHVlRlUyVUhacVEwNVpWazgyUzJKbmNEZFhWVFpTY2pSeVJURXdSbWczVVMxaWNrSmFVSGhDWTJSNlNtOXRSVEpDZGpFd1ZIQjJPV1J3TkUxdE5WbDVhVVF6UTBKd2FIcFdaVjh6Y0VWa1MwWlJSVTVvWTA1Wk1HdEVlR1pHT0dodWVucEhlbEJKT1ZkWFREYzRjV3hxYjI4MFNtTnRNRUpRVVhCV1dWbzBTVmhqWmt0WFJsWnNXa3R6TjJGVk5GbGtNa0V6UjJwck5tTk9UR055ZWt0dVVraHdUa2hwTldKc2JqWlBXbWcxTTJOcFJXNTRNVXRSTUhSUFZXZG9ibEpUTjI5dU9FTmtUbFJHWkRkUVIyUTFNV0pGZUhKVVdrZ3lZbmRWTldsd2RIY3dibXhIVUZBNVIxZzRTMk5pVW10eVIwUXlURUZGVVZOdWFtbHRkM1pYVlVkb1lVVlZOMVkxZEc1ck9HZDRTMk5rWTFOcFMySXpaelZhUlRRMVNFVlNMV2h0TlhaU2VWbHRRa1kxVmxSeU1uWkNVbFEwYlc1Nk9WSXdTblJEV2sxcWFrWlNhM1ozV0hZMFFXUkdORFpIYjJOSVlteHpZa1p2VW05VE5UZDFheTFCYzNFNFpHNUNSelUwWjFKaWRESk5Ta2xMVldkRGRFVm9ZbU4yWmkxSFVuY3hWa1kwTmtGUGNGZEJTQzFJTm05UE0weDZRMDlZVVhKSVRWQkxWakpVVlZSSldrd3lORUV4T1RWbE5IZGlhSFpQVm5sSlVuRlBPVlp1VW1WNlVYUlVjbVZMU0ROaVN6RlFYM0JWWlVFNFkxRXdhSEZvUVhKMFdYaHRSMlJyZEdGMVZIbG1OMWhsYVhGT2FXSjVjMFZJTFZsdWVGVkZia0ZtUjFsa2JESk1MV2Q2WW1WRmJ6WXhiV1U1WkcxUmVFUnRReloxZG5OTlZHbEZNMXBMVUZkemMzazNlbTFYU1VkbGJtVXlVMjVMUzNsNmMzWXdaRlZMUzA1TGMwdG5OMGsxZDFSb2RrbFdSVFI2TFZCdlowOVpjRkZWU1ZkMmVGQnhTblE0TFZoNFgyZ3RhbTlJTWtSMWNqUktiMEYxYXkxdlpHcG1PRXhqVG5OeGRHY3VhSHBoTlVkb2VUSmFOMFIzUW01SVNYbEJTMXAzWncuQ3JMWFhqUDZTbERFVHdTU2ozSXZ6bDVsSGdzazVTZHpmby14WlJCQzVITSIsImV4cCI6MTY4Mzc1NzU2NCwiaWF0IjoxNjgzNzU3MjY0fQ.CridMM7bwY0S0xESITD47gmmqnS2IUHv_XXedo4mhEY',
  callbacks: [
    {
      type: CallbackType.NameCallback,
      output: [
        {
          name: 'prompt',
          value: 'User Name',
        },
      ],
      input: [
        {
          name: 'IDToken1',
          value: '',
        },
      ],
      _id: 69,
    },
    {
      type: CallbackType.PasswordCallback,
      output: [
        {
          name: 'prompt',
          value: 'Password',
        },
      ],
      input: [
        {
          name: 'IDToken2',
          value: '',
        },
      ],
      _id: 70,
    },
    {
      type: CallbackType.DeviceProfileCallback,
      output: [
        {
          name: 'metadata',
          value: true,
        },
        {
          name: 'location',
          value: true,
        },
        {
          name: 'message',
          value: 'my message',
        },
      ],
      input: [
        {
          name: 'IDToken3',
          value: '',
        },
      ],
      _id: 2,
    },
  ],
  stage: 'DeviceProfileLogin',
};
export const confirmPasswordStep: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlRFU1RfQ29uZmlybVBhc3N3b3JkIiwib3RrIjoiaThocm1iN2dqOTRkNHRna2Y3Z21wZWN0MTYiLCJhdXRoSW5kZXhUeXBlIjoic2VydmljZSIsInJlYWxtIjoiL2FscGhhIiwic2Vzc2lvbklkIjoiKkFBSlRTUUFDTURJQUJIUjVjR1VBQ0VwWFZGOUJWVlJJQUFKVE1RQUNNREUuKmV5SjBlWEFpT2lKS1YxUWlMQ0pqZEhraU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYVhkcFdWZDRia2xxYjJsYVIyeDVTVzR3TGk1SmRGTjRjSGsyUlVONlgwWnZUWFZzUTFvdGVHZDNMbTlwTFY4emJsbFhhbUk0VDBSeGJuWlFjRWRhYW10T1RYWm5NamMyYVMxeVZsVkxkSEZPTkV4ME1uRkpkMWxJUlVsUmJHZHFkMVpoTmxCMVVuQklNWEoyYUV0YVZGVnpWbTAzV0daVk9YRkJRazFVY0UxQlNHeHVPSHBmWkhOQ01GWnlNVm8zYUdVelYwdEhNRTEwY210clZYWklVelZoVkRVeGJUQTNhRWN6Y0cxMVlXMXZkVGMwUmxGUFUwMDNaazlvV0ZCR1JtdHJhM2R0TFZZMFZsRnJXVmQwTVc5M1JHcFVOMnBaTlZGVFh6QlhiMlp4YmtRdE1UZHpRV2hTVjBaUkxVMUpNVFJoU25STlIxWlBNMHhCVlc5TlpXbFBZM0puYUVWMU5sSkRPRU5GWjFrdGVVbHNjRVpxV0ZSUlIwYzBPRmxvVERVM1RuTlJWR1ZZVlVGbk5GUkpZemxEUTB3eWRUbHdTWEpPUTBnMFNuVXhaa2hqU0ZsU2R6RnVUbkJwVGpJM00ySkJXSE4wU0hKb1FrdzFVbmhyVTBFNFRIbG1RbEpWWVZCV1NVeExRa1UwZDFWdWVuaE9jVTVGVkUxdlpUUnNNR0Z1ZVhGaFpHVTVTMkpaWmxobmNtOVVaMEpLWmtOV2RHWlBSWHBZV0VGT1prOWZXVm8zTlVkek5rcElVM2hsZEVoSU1tNTRhRVJEY0dKblp6SkVlbTUyT0ZGVWVsOTBNM0ZsZW1OTE9YRkZZVTVVYmxadVFqYzBkbGR6ZWxRMFYwbG5iM2hTUnpSTVNFMURNRzVKYUZCSU5IWmFlSGQyY0ZGWFpsaFRVbGRDY0VGUk5sUjZhalZYT0Y5cmVYTlNaRUo0U0hBMVRuVkRVa05CWmtSeFRVTjRWMVJ4VDJWMmVrTlViak5TTm1sVlkxZG1OV2RTTjBzNU1UbFRUMVZPVUV0eFVISk9jWFEwYVZWNGNWSllMVmRDYkRkM09GZHlNVmh3Ym5kdVYwZGtTRmRSYjBkTmFuZDNMV2d4YTFCQllVeG5UMFZaU2pOTmRVaGhWbVppYTJ4U1RteHhZekk0T0ZWRFgyODJSWEl5T1U1YWExVXdaMmx4YW5wT2JHaE1hbWc0WkZkaVFUbDZaRWhPVmxWUlZ6VkRSVjlwTUd4NFFrVk9VbUl6TWpKdVlsa3hVakowWVcxWFpYSkNZbmhHYUVWV2NFMWpMalZqVWkxMWJFNXlNbEpWWDFWSFVHVkpWazFxVFZFLmhnbll0cTRzWVJWWjZzU3c4cEhfT3FLWFkxT25GN0xUaE9DUnhrLWtUVFEiLCJleHAiOjE2NzQxNzI0ODgsImlhdCI6MTY3NDE3MjE4OH0.2M4EMYwOxms_0UrtqhoE5-DCE4Mfkcuk7ShpuamnYzs',
  callbacks: [
    {
      type: CallbackType.ValidatedCreateUsernameCallback,
      output: [
        {
          name: 'policies',
          value: {
            policyRequirements: [
              'REQUIRED',
              'MIN_LENGTH',
              'VALID_TYPE',
              'VALID_USERNAME',
              'CANNOT_CONTAIN_CHARACTERS',
              'MAX_LENGTH',
            ],
            fallbackPolicies: null,
            name: 'userName',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              { policyRequirements: ['REQUIRED'], policyId: 'not-empty' },
              {
                policyRequirements: ['MIN_LENGTH'],
                policyId: 'minimum-length',
                params: { minLength: 1 },
              },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
              { policyId: 'valid-username', policyRequirements: ['VALID_USERNAME'] },
              {
                policyId: 'cannot-contain-characters',
                params: { forbiddenChars: ['/'] },
                policyRequirements: ['CANNOT_CONTAIN_CHARACTERS'],
              },
              {
                policyId: 'minimum-length',
                params: { minLength: 1 },
                policyRequirements: ['MIN_LENGTH'],
              },
              {
                policyId: 'maximum-length',
                params: { maxLength: 255 },
                policyRequirements: ['MAX_LENGTH'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Username' },
      ],
      input: [
        { name: 'IDToken1', value: '' },
        { name: 'IDToken1validateOnly', value: false },
      ],
      _id: 0,
    },
    {
      type: CallbackType.ValidatedCreatePasswordCallback,
      output: [
        { name: 'echoOn', value: false },
        {
          name: 'policies',
          value: {
            policyRequirements: ['VALID_TYPE'],
            fallbackPolicies: null,
            name: 'password',
            policies: [
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Password' },
      ],
      input: [
        { name: 'IDToken2', value: '' },
        { name: 'IDToken2validateOnly', value: false },
      ],
      _id: 1,
    },
  ],
  stage:
    '{"ValidatedCreatePasswordCallback":[{"id":"db09cd18-65a7-424a-9c9e-84c528c3e560","confirmPassword":true}]}',
  header: 'Quick Register',
};

export const loginStep: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkxvZ2luIiwib3RrIjoiNmwxb2RmdWFzbjBxMXNrZXBjZTUzZmMyNCIsImF1dGhJbmRleFR5cGUiOiJzZXJ2aWNlIiwicmVhbG0iOiIvYWxwaGEiLCJzZXNzaW9uSWQiOiIqQUFKVFNRQUNNRElBQkhSNWNHVUFDRXBYVkY5QlZWUklBQUpUTVFBQ01ERS4qZXlKMGVYQWlPaUpLVjFRaUxDSmpkSGtpT2lKS1YxUWlMQ0poYkdjaU9pSklVekkxTmlKOS5aWGxLTUdWWVFXbFBhVXBMVmpGUmFVeERTbXhpYlUxcFQybEtRazFVU1RSUk1FcEVURlZvVkUxcVZUSkphWGRwV1ZkNGJrbHFiMmxhUjJ4NVNXNHdMaTVrTVhnMlptVkJNVmhZU0ZnNFR6VlNTMmRTUTFKQkxsQTBVV0p4Um10Tk5tMDRSblpNV1Y5eVZ6UnBZM0IzVlRneGIxUkxUa3c0YUVweE9UZFNOSGhHYzBGRVpIUjVRVlpMVVhab2Vtd3hjRkl6VVdsMGNIaENVV1pPVVhSbmFWODJlUzFmVGxCR1UwMVJkRGhNT0VSMGFVUk1UMkpHYUZsck1XSnNYMUUxU1ROQlRHd3dRbXRGVjI5TWNUaExTR001V21SbVpWTkZRVXBOTjBFMVEzQTBaRzQxVEc5cExTMVFUWGRoWnpaM2FrUkxORWxmVldKWllXbFRTak5FZGxkclQwZFpSVTV6V0hsSWFuY3RjV0o1WlV0emR6RTBZVWR6Ym5CdVVIVnNWbTFXWkZOc01XMUViSFUyTmxsNFZXOUhUMlZ3UVRKU09VSnVVRE5rYjBOWFMyTXpkREJqWXpVMWFqRm5lUzFYYzJabmVGTmlWekZZTlhkcVRtZFBVR1ozWW5SNVRISktjMHRwYzA0eWMyTTJWbFJ1T1RnMFZpMUVWVzVzVjJRMVN6QlZVVXBPY2w5MllVMURUMUZtU1hSM2NFc3lYMnhZWVhCdE9VVjNWRW8zY0VwVmQwVnJabHBKTkRWM1IyVlBVMGRDVlVaWlp5MVVhV05IVEdwT2NrcGZXazlxTkdKZmVXMWphWE5SU0U1WFdGOUtZeTFRZFZJNGIyWm9RbkE1U1RaRGMyWmZVbGcwWHpKUGJteDNVbDk0Y0d4dFUySlVSVlIxWTA5UVNHTnBkSGx1VjFsQ05VaDJObnB4WjFaNmJ5MDRNMkZCUVVzdFQydGpZWHBNWm1NeU1XYzNNbW94ZWxCU05HWnBhbUZaYVhGRFZGOUVhWE5IT0c0eVV6RkZUazF5T1ZOV2N6QmFjSE5WYkRKWlYzUkplSGhqT0MxMmMxQTBiaTEzWnpsUk5XcExkbkozWlV0c2EyOU9WazVETm5wT1dDMUNhbll6WVV0dFVUTjRVbVJxYUc5eU4zQnJSSFI2TUZKU1RHcHJXaTFYWkdwb05UaFliVFJtYTFKVFJFOTJWMHBLUlZJNVFUUmtXbEZHZEU1elQxcHBTR3BWWjFOdFgzVnpNSE4xZFVwR09EZE5hQzA0WldGd1YybDFMWGgzZFZaeGNuVk5SV0pQVmpGR1J6ZFJUbmRNU1RBdGJWWmlja3gyZVVsS04wNUJiamhxVEZZdFlsZHFMVVp1Wm1vd0xqWlBjemhUU2taUFNUaDRPVzgyTkV4NVdrNXVMVkUuRGpTUGdQck5VdFQ0U2JKWm9fZ2NiUlZCbWVQcGRHcUZzb1UyM250dVNCdyIsImV4cCI6MTY1NDIxNDQxMywiaWF0IjoxNjU0MjE0MTEzfQ.ZGwMWJb5crNXiAvvfvnwciOTyXaAKHjSk-aExg7QdnQ',
  callbacks: [
    {
      type: CallbackType.NameCallback,
      output: [{ name: 'prompt', value: 'User Name' }],
      input: [{ name: 'IDToken1', value: '' }],
      _id: 0,
    },
    {
      type: CallbackType.PasswordCallback,
      output: [{ name: 'prompt', value: 'Password' }],
      input: [{ name: 'IDToken2', value: '' }],
      _id: 1,
    },
  ],
  stage: '',
  header: 'Sign In',
  description:
    'New here? <a href="#/service/Registration">Create an account</a><br><a href="#/service/ForgottenUsername">Forgot username?</a><a href="#/service/ResetPassword"> Forgot password?</a>',
};

export const oneTimePasswordStep: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkRFTU9fU29jaWFsTG9naW5XaXRoT1RQIiwib3RrIjoiNXRzbnMxa2duOWgxOWVoOGZtbThrNGszMnEiLCJhdXRoSW5kZXhUeXBlIjoic2VydmljZSIsInJlYWxtIjoiL2FscGhhIiwic2Vzc2lvbklkIjoiKkFBSlRTUUFDTURJQUJIUjVjR1VBQ0VwWFZGOUJWVlJJQUFKVE1RQUNNREUuKmV5SjBlWEFpT2lKS1YxUWlMQ0pqZEhraU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYVhkcFdWZDRia2xxYjJsYVIyeDVTVzR3TGk1NGNUWlFlWEJvU2t4TFlVSnZhbEEzTURrM1JVSlJMa00yYW1nNFZrWlNZVkozZUVKSVpURlNWQzFXYVhoMmQydENVMlZRWVUwM1RrUmplRFJIWVY5eU5ESTJhRzVDYVVObGNEQnlVekI2T0RBMlNFZDFlSEU0WDB0U09Fc3pabmx0YkV3d1FWZHlhMlpGVDBsRGNVaFFYMDFXWlU1elRsbDNObVZ5VkROcWJXRlBNUzF2YVdKQ01UVnlUV05GVVVaVVZVaGtkelpPYzBkaWRHazJOMDFrTVVzeGVrWlFMVUZwTkRCb2MyWlRZbUozVTJ4cE5GbE5TazFOWlZWNFpYaEpWbTFRUjJsT2MzY3RXbWRaV0hsMk5HWXRWVTh6YjE4NU9VUjVTRGxHWXpKd05FRXlWWGhRU2xjMVkzazNWazlFU25kdE9UVlZUMTlpTkVGSldIUk1NSFJoYUY5V1ZUbDBVVU5LY21OME9URkVkM2xtWjFneU1IVktOV2RJYzE4M1NDMTNhVVpoVEdvMVlqVkdUV2d3Y0dGTk1YTjJkVEpsWWtkRlVFRmphblp3YzBaRFVrMWxhMUpXYUVwRll6aGlWVUpUTkhwQ1pIWkpkVUZOWlU1cFowUTJSVTh6ZWpSRGNqWlFaWE5oZGs1TmJHczBRV1ZGTUUxeGEzTTBkVXhaVFhCaGJrUlNNVTFKU2t0UmVHVnRZMjgwTlVsa2FWcHRUMFkyWmpjMVVFZGZTRlYxV1RrdFYwTmpTUzFPWVhaVFkzTnhRa3hEWWsxWmFUaGtTRmRzY1dKeE4yeElibUpMVWtVdFRsb3RVR2xFYVVkT1YzbGxUblE1VFV4dE0yVm9ZV2N3ZUVaWk5reEZRMUZVUm1KTlkzSkJWbVozVGpFNFgwVm5ZMmsyWTFGcVozZE5VVkZEY1Zsa1JXUmxSblJqV21kV1dqTmtXVVJJV0ZGQlkzZFNha1oyV1RaeFRrVmxVa1JHV1d4NVZtSldUbWM0V0hwQ2FYbHVNVzlIYm5sTWJUSnZXVEZxY3pkRlVWUkxhM1ZXUjFOVmFHSm1VRVI1YzJZeVYyMWplVkZvYzNsNVlrRTVhRmRxYVY5V1YyaHdZbVJaVERkclNrZ3RXbEE0ZGxSNGJVaDZUSGxKTkdwb1owUkRRVU5IUW14c2JUTjVTMms1T1ZKMFpHVnlhbUp6V0ROaFNXSnJNRXhVWmpGS0xYWlBjSGQyYTFsaVZrWm1TakJuYlVWcmFFTjJZbmx2U1hSc2NFOVdibGhPUldKSWJGSXdTRkZCY1hka2RubFpUa1IzVFRSMVgyaGpWbmRsY0ZGb05tWllZVWt4WVVoWlRrWnFaVVoxVFhod1VXcElhMEZxUWxNNWVGaHlUSGxNU1hWUVpYTlpla3BIT0VNNGVqUjJSRmwzWW1VME5EWlFiV010TXpKSFYwNU5XbkpDT1U5dk1ERnJhREY1ZVVGcmNtTmpTamgzV0VFNGJrNUhOa3RHVEdob09GODJla3gxYlhCemJVTXhXamx1VjBWYWRGZ3piMWRmVEVkYU1raERORXBoYmw5TVMzQnZhMjlEVmxaRmJXNW1aUzFsUVVkaloybDFaVVUwZVhCaWIwNU1ORzFYZFU0eVJUaG5WMnRGWVdacE1FOVBialZTY1cweGJVcERTaTFpU25CMFNsWkNUblZ5WVVWWkxXcE5NRTUzWVcxMFNXZzJjMnhZY2s5SGNHSm9lWHA0Y0RnelgyNUJZbmR5UjJkdWFqTldTM2xKYTFCTVNVRmtiMU5UVkdOd1pGVmZUbTF3VTFSdlltZG1iV1JpVkZoR1JtNWtabUp4ZWxKVlZtWlBhVEF5VVdJNVMzTm9ZMGhwVWpSRU9IWldOekF5U0ZvMk5GcG9SSGRzTTNoMVpqQllXVGcwZVRsSVpITlJlV04zY210WVZUVTJSekZpVDJoaWR6ZFFRMGMyUTNSaFFqSk9VelpWY0hkd1RXRmhURWhrVkRKdFIxWmxNVE5mVGw4M1dVdEpOWG8zZUcxdlVFVnRkMHhWVjJRNFl6SkdkVTkxVVU0M01HZEhPVmwzZFd4VVVUQXpWVE0yUlhSdVUxYzFYM1J2VkZBNFFVWmtaMUZHYjFORVdrZFRNRTQ0UmpkeVNqSm5RbFJXZDE4NVNFNDJlWFowVlVOYWExTjFUbWxFY2pOUFJITkNka05SUzJjNWMwSTBkazF6WmtweFVHZGtablJwVjJNMVpYQklhSFk1VGpWbU5YZEJSSGxyYkhnM1pHRXhjMmxYZWpsV1ZISXhaRll4U1dRelRsSlJVbGhZUlUwMlFrMTVhMWQxYVVScmFHVnRWWGwzZFdSU1UwZEhOMmt0TWxkVE5YQkVkRGRyTldGWGVFeG9VVzVOTUhkSFEwVnlaMmwxV25ReFkwUjVTRUZSVTJrM1gxOTNXSGRTY21kVFVHZFhiR3BwZG01cVRuSnZRVzF3ZFZWYU4zYzRjakJvU2pkSlpURllWVlE1YVhwS1VFNUdiV3RIYTFKalRFTm1RemRNVW1aRk9XUktVVFo0UzNOeWR5MXBSV2xHZVhVNFpqQkNZVVZmT0RkdWIzUjZOSFpaWTFoelgwUTRUMFZaVTA5RkxXbDRTR2d6WTNOMVIwaHVOVkUwWTNkd04yOHhSWE5FVUZGbVQzbzJPRjlwUkVac2IzWXljR0Z6VlhOTWRWZzNkVkp3TjNsSWQwSlVla1psUW1OaWNrMVVMWEZJWmpsWVZXWnZTelJ6TUdkd2JFNDJXSEZpU2xjelJGTmxVbTVGYURCcmNtSm1VbHBzY0d0a1ZXVnlaRU54TkVsU1ptaHpVbmh6YVRKTVVWOUJhM0Y1Y3poQlN6aEpielUxTldFdE9ETktiME5RZVRaV1UwZDVRMTk0Y1ZKVlluVjZUemh5T1hKTk5Xd3pVWFZ0TTFKMldXRkxaazVuU0ZSdVFrVTBNWGxxVUdSZmRrOTJSM0JWVlhsalpISTNjWEZGVDBWWFREbHNOMnRVY0hoaVdsOUNTWEJGUVVwNVRHbGlRVXhqVkhCR04zaFVZM1p3YkhwVFNHcHRPVmhETW5CQlprdHhkRXg2VHpGb2J6QlhZVnBEWVZWWFowZHRUMHBRTTAxYVFqVjVTWHAxZFZCYU9IRmhOekUyV0dScWQzUTVhR0pwU2t0Vk1uSlVkRkUyWDA1eWVXMDJRalZrVVc5TlREUkxXVmw1UmxweVVWODNUV0pSYUVabmFtZE9jekJFZERGaGQzUXpiMGRrWkZjNFIzRlhiMWxqUzJvMU1FRlpjSGs1T0hoTWFrUk1aMUpvUzFaTVVqbFhPVEpmTUdKQ00wRnRabWg1ZGxJMlVtZHFOeTFQYURkWUxUY3pSSGMzZDNwMmJEWndSR05VU0dKUFJVVmxUVFYxUlZCc1ZVMU5jbGhoU2t0TlRGOWhSelUzYWxkVlpqbGlkMjVXVFdGUVlsVk1jbFpPVjJoMVdVZHVTM2R0T0hGSFpUQnNNbU14YUV0RldHZGphSFJSYTAxdFIxRTFiMngwTFdwcllUSndURFIxWnpsd1JrbEhZMDR4YkdOdFRuRmZlVEpSWm5Sc2JuRXhSV0l4VFdoR1VEWTRPRE15WTA5UloxbHdXRGRLT1VwRFJVdEViMlp0TWtKalZYQklOVEZSYUhSeFVHNW9YMjVITkV0UGQxRjNhbTFaU0c1R1QwRkRSM1ZKZERRM1lUYzJSR0kzUlZsQmFrb3lkVEl0UW1aWExWSjZSazVxWlhsM2NFdzFWWEk1UmxWa05ISkpWMDk0TFhjeWJpMVJiM1p1V0hOWFNUSmpOR055YkRSYVptMUZNVjlaV2tGc2JWTlZOWGQzUW04NFRtbzJVR3hLVjAxWVJEbERaMlp0UlZkV056Y3lWMGxqTTBrMlVYTlhOMGN0V2tFeE5XeGtiakF4VTNNNVQzSjRZVnB2VUZGRExUQmZkR05JWW1ORFFrWklSbXBMT0ZwUU9GRnFPVEJ6Umxkd1ZraHhNbGd3TFMxS1NVRjNjazgwUVRSU2JEaG9iRlJFV1ZvNVJtVllXblZPTTE5V2FtVnFVRmxoVFZJd2NtSndOblpxTVU0eWJYbGthblJOWXpabmRteFlXRWgzV21kMmJFUlNaVFY2U0VsVVRWcFFRbEp2ZWt4TE9XZG5WRE5LTW1sblNqbHRjWFpoVGpGbldFRnZkRUp4TUZoclQySlphMk5DVm01elJrbEhORGhSYkdKNVZUVnFZa2RUUm5aSVRXOUVNMVZrVDJWV2NFOVBNRUV0ZGsxM2FrSjRlWFZETmxCc1dEZ3hjRXQ1WW5wT1FVMUZVbTFYWkhKUFozWjFia2t4UVRoalNtSTJUa1pwTVVFelZVRnJaV3BHVmxjNWMzZEJSSHBWWmxaNlkxWktZMUEzTUVsaFJVMWZkMngzYjFkRmNtcHJZM0F4YkZkcVJrRjBaRGs1UTIxTVRVNVhRemxEVjJFeFFYbFRlVWxVWWxJek5rNVJUSFJqYUV0aE5XeFlYMEZuVjJrMlEySlRYMUExTWtWTlQyWk9Za3N3YkVKRFZHWmhiV0pGWWxOQ2NUaDJXR3B0U21wdlJYZGxObVZSWlhSSFFYSlVkRXA1YVRoZmNUQnBlVVV3ZFMxUlRHWm9kSFJIU1ZKQ1JHSXdSVlV6VGpCbVNFMXBVVkUyVTNWVmEzRnNia3RYTTA5MlVVZDNiVFl3VERGcE1VUkRiVkpSTUd4Tk1YcEpTRW94U1VRd1ZTMXpTMHN6UnpKR01rMDNhWFZMYm1Wb1dHaEhUMGMxY21sd2JtczRiR0ZuV0hrM1ZVTXdaMmR0VFhZd2NEaG5NRU5rVG5BMlpFTnhXSGwyYkd4VVpreE5aR05VT0Mxb05rdDNObEl4TmtseWRIVjJWMUl0UVdWME1DMXBibUZKUkdScVFtcFFRMTltY2twMmJrbHhZbWhEYlc5NlFrTmlXVmh4UXpKbE5VTklRV2RTTUdkNmMyRmxkVE5VWmtSRFEycHhkVUpQTldoRU5sOUlWVjl1V0VGcWVURnNORlpvVUhwb1JUVTJRbFp5Y21Jd2MycGxkVGh2TWxrM01FaFRVa2xFZDBwVk5WQjBhbEpCVkZocFNscDJOekpRVVdWcVEzaFJNRUkwUWxaZmQzaEZUakF0UlRCbGFVeE1TVGxyZUZndFVVSnpTbFkzTjFsRU9FaDNVMGRUZEdSd1gxUmFVMFJLUVdKelpHbHpZV2hqVVU5VFYzQlZYMFZrWTFOckxWUkJXbFJGVEUxUmIzQTVPVzlMVGxaUk1VNVNWV1pMWDB0ZmQwcElRV1J5U2xOWU1HRjZNVEpzVW5kYU4xUTNNWFZ1T0Zsc2VWWk1VbEJKY1UxTWVsVlBYMmxhYW5WVVRqSXdlRWxuTVdGbVlYZFBSVXhIVkZoSmVsRldTVUo0ZEhKYVpHSkJRbXR5WVdWQlJEUm5SbFUxY0Y5UGJVWllRVE5WT1hsRE5sQTFhbEl6WWpKV05WQTNhMVE0ZDJOemJGSnliRTFNTkhGcVVsUllNV0pMTVhsTVp6VndZMWcxTmtoVWNuaEpNM2hSUWxBMVMxSkVRbEJSYXpSTFJVeDFPVk5hY1VGeFFXVldXV2czUzBGc1UyRkpXQzF5TkdWYWJXdzVMVmh0ZFdOeGQyaHFaa2RSYm1Wa1dFWjBha2xLTkVkV1RGaDFUM3AxVG5aU1N6aEdiQzFaY25scmJuWlZhWFpCU21wSlNEaHdiSFZVZGxod2RFSkNiV2hVZVVGSWQwaG5NSHB6ZDFsdlZqbExMV3BVU0VSR1dFZHdZV1F0VUZkS2MwOU9UVEpaU3pnNWJuWTBiMWxxU0ZOUVNGbHVXSFJNVEZRMFRXSlpia3BaVFd0YU1GQk9Na0ZTTUZsd2FVbHNhM05DYTB4V0xVRnRTMjQyZGtveVVuUjJObTF3TnpsUmRFeDZSVGs0UjFWZmQyRktlbEYxTkRNMGRrcGlRa2hFTlVRdE1tOWtXbE53Y0hwWWVGUTRlRVk1ZFRWSWEwOU5lblZyY2xCM2VFWk1RMU4wTFV3d2VtMXpXVUZrYUhkWlZrUktaVGhCVG10TlRGbHFORTFGUmxaMGJsbFRiVGRWUlcweVpsUmpRa3RxWmtaaUxXVlFRMnQyU0ZCRU5uVnpkVGRYZFdWb1oxVlZUVVJHVGpWYVlYTjBWRTVaZEc4eGNERnVNM1p1UWs0ek1EbHVXbVYwU1djNFIwaFRablZJV1Y4M2VIWXdhV1V0WDJoUGJYVllRVWRFUkUwMVQxcElaRGg0WjBka1owaG5hbFpwV0V3NWNUWjVjakpITm5wRFlVWk9lVUUwWkZSdFFtTkNlV3QyVUU0dFpsbGZlWEpKVGpoVGNVZHJRM1ZYZW1odlQwdFJYM0pxVmpoTldYRlBiMFJrZFdwcGNGSk9WbWxUZDFObWIwcFBRMFJNU0ZNM1VXbG1VV2hTTlhsYVgxOXZjbEJpTkdSNWFEQXRPVGM1TFhCdFJVdFVSa3gyUkZwbGRIUlhjVkZ6YkdSNFUxVllaVE5MYUhsME1HSmFURTVzVkY4d1dtRnVWMkp3TlhONFNUWmhiM3BwTlhWb1VqQTJVM2M0YmxFMmIwSlBXamg2YUhOaGNFSkpOMTlGYm1SV1VHaGlPV2hvV1dsWGFGUnBNRmg1TkVsNFdVYzBjbVZWTUc5V2NuTnNOMTlrWkRkMVNtTmpMWGt5WkVOU2FYcEhWbkJDT1ZwR1ZuUlpXV0pYZGtkbVFtTmlaVE5MTTNRM1IwcERiRkZrZGtwcmJGQlFTakZSTjJaeVRUZ3pSalExTlZGZk9XSkxja05IVWpWbUxVOXhORWszWm1OV2NITndhSGxsZEhKeFkwOWZNMnBLZEVKb00xSndialV0VFhwRE5pMW1la1kyWldsU1JFSnFNMmhDY0dOS1QyUjRWRTV5TjNGbWR6TjJXWFpoVTBWTmNGRXpaRTg1U1U1WWRFa3hPRGxDUm5sa2VubGlVbmhTTmpWU05FbDVVMGhpYlU5MmNVRjJVVGhtZFVRdGMwSjVXSFpyVmpkM1RURTVkVzFxY3pWR1ZUUXRjRGxSTFRaVGIyaFlWRFZ3WWxWYVNVMVRaWGxpTFZSV2RHVjFYek5ZZVRNeVR6aDVialZET0ZFM05URklkV2xUVFVsSWNXTkJhV2xCT1hWSVUxOXpUVEZKVjFkVk5rWk9PRWQzUVU1YU5uTTNjMXA1UXpkYU5qWkVlREJ3TW5ZeGRHMVFVRzFLT1ZoMFREVkpOR1IyYjAwMU4xcERZMk42Tm0xR2VYSlFUa0pmUlVSbFVsOVJiWEpFVW1oSFlXUjFUSHBtTVZOaVozcERVVXBXU0V4aVNtODFZVnBmV0VKRVkwTXpZMHMwY3paMFREWlJiRkJJVm5kelVrcEthVm8xVVdGMkxTMWpPVmd4ZDJOS05scFdhek5ZZEdveFRVNTZZM2xHU3pFNFpYRm1kVkU1TVV4MWFXb3piamd6WldkV1VVZFphMDlwTm5KME5sVXdibk0xTmxsU05TMXVaemwwWjBKYVpWQjNTRGxXWDBKVldsTkZaMnBYUzJsdFdWUm5kRGRrWkZScFdTMUlNbEpUTjBScGVGaHhYMlZRVkhCSE9VaG1TbkJsYmtadldVdGFZekozWm5GaVFVTjVRamsyTjJ4VE5sUmtZWGxuY1MwMFZVdEtWSEJsZW10NlVIZFhXbWhmTkUxT2FVOW1VWEZaV2xwdFFtMXpVVmR4UlhGVFdrVjRWVlo0V1RoV2FtVmZRMFZyUWtWbFpqWnFNWE5yY0c5S2NHVm5ibWs0UTNCeFEycFRUMVYzWjJablFtOXpkSFJGUXpsTU5VRXdMV3BJVm1wUWVrczNhell4V1c1eGMzTmxUM2N1VFRReFgzcG5lR2hhTmtWV1UxcDRRMTlQYTBKVFp3LlpjSEpEUnBMczNFNEVKb1c4WGY2TXY4RkhKdkZibDVGbmE2LXdmd2NiSjAiLCJleHAiOjE2NzcxNjU3NzcsImlhdCI6MTY3NzE2NTQ3N30.YPVZCdJbqwLp-HcVllCVXSd-j7EdVQ5XZ2ehMlTxjxA',
  callbacks: [
    {
      type: CallbackType.NameCallback,
      output: [{ name: 'prompt', value: 'Enter verification code' }],
      input: [{ name: 'IDToken1', value: '' }],
      _id: 3,
    },
    {
      type: CallbackType.ConfirmationCallback,
      output: [
        { name: 'prompt', value: '' },
        { name: 'messageType', value: 0 },
        { name: 'options', value: ['Submit'] },
        { name: 'optionType', value: -1 },
        { name: 'defaultOption', value: 0 },
      ],
      input: [{ name: 'IDToken2', value: 0 }],
      _id: 4,
    },
  ],
  stage: 'OneTimePassword',
};
export const recoveryCodes: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlBhc3N3b3JkbGVzc1dlYkF1dGhuIiwib3RrIjoidXVnOHNxNjNwNGs2YnRzN2NoOHZzYnVjbDQiLCJhdXRoSW5kZXhUeXBlIjoic2VydmljZSIsInJlYWxtIjoiL2FscGhhIiwic2Vzc2lvbklkIjoiKkFBSlRTUUFDTURJQUJIUjVjR1VBQ0VwWFZGOUJWVlJJQUFKVE1RQUNNREUuKmV5SjBlWEFpT2lKS1YxUWlMQ0pqZEhraU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYVhkcFdWZDRia2xxYjJsYVIyeDVTVzR3TGk1SVdHRXhaek5EZUU1MldGZFhVblpzV0ZOdVNtVm5MamRuWkZkUmFWRlZPRmhQUWsxcFpuZEZjMWx5T1U0MFlWaHdjbkJ4V0ZGT01IQlZaa3BTUjB4WFVUUnBkR3BNTFRKblVGUkJlbEpPVW0weFJTMVlXRTlzVGxoRlluZEVSVmxvUWtSTlozbFlZVWxaVmpZdGRGSmFOVmMxU2twbU56RTVTSFZGVFV4T2VHeHlWSFpHVkVJd1UweHBTVWxQWWkxMFExY3RaVFZ2ZWpWM2NDMDVUM0ZKZW1KUVUwazRNRk40Ukc5bU9FRllNbWhoVVhCeFVrVnFSMU5oWlVsaVEzTjZNWE53WWpOVGExUXRZVFpVTTFWUk0wTkZjRnBPWDJGWmRHOUVaekJRVW1ad1FVOW9aV2c0WmxGVGNWRTNiVWxmYzJOSGVURnJZVTVUWWxjMkxVRlhZVll6YVdoUVNDMTZjbHA1VDJaU1EyUlBTVVpPVnpoMVdXeERUWG8zVFRaemFWODJZVlpSTVZRelltbzFiV3BDTFZrMlIwbDNSR1kxU2pSeVh6SlpZMWxsYzBsWVpVcGhhSFJHWlRSUmVUVjBlbVp5YkRWd1Z6WTNUa3AxVEZCMVYzSlVObkI2WDFBMGRGbG1UM0l5WjNkRE1UbG5Wa1ZxYW1KNlZVUkRkM0l3VERsWFNtbE9NM3BIZUZoeUxWTk9WMkp1YTBscFVtNVBPRWRoVEZSaWVFSk1iWFl0VEc1dk5IQjJRbGxIVWprNE5rNVdjMFJqWmpKVWFrZDBWVE5mZERSbVptRjNaMnRyWWtOclJtdDZXRFV5Wm5RME0ySlFabGRMWmtaRE1Fc3piRlpoT1ZGalozbGtVR3c1UW5WeU56bDBTbmR5TWtwSGIxZEpTRXB2VDJWbWIwOXZkekJTUkRkWWFFbDBTMVZoTVMxdFZuTlpaRnBDVG1oWVpuQnNlVW96TTFGRE5IZzRiSEV3VG00NVNWOW5TV3hRVEhJMmNHRTJaM0JRYUc1aVNXVkpkVGhRTUZac2FtSjRjbk00Y1MxRlEycG5VRU40ZFRWSVdHZEVOVVZxTVRKelozVjVWV0Y2WDAxbmVVNWhaV3Q1Wm14b1MydG1RbkpsYWxOamJuWmtSRFphWjJoTlowaFpjVE5EWm5oUE9XZ3dkbXMxVWpSME0wRktTbTl4UVU4MlgzVkVTRlpTVWpWNVdWZHNaVEZNUWpadVpFVnhOVTQzWW1WMlRGbFRZbTUzYW5sTU9HVmxaMDlmYnpJMWMxcG9iRTl1TVRaamRrTTNlRmh6T0ZOSmNFcDFVM1paVjJaVWJqazBWR3hHYmtOVWNFMXdhMWcxUVdOSVFWSnZWa3hNV2xSdk5YRXlNbEJpZG5oRGIyaG9hRkJKYTJGcVIwMTZlRmh1Y1ZCSU1VNHRVVGRRT1VSRk1WYzRXRzV1UjE5RmFrbHhORmRtVjFOeFluRmpjMngyT1haWU1XZGxSR1ZXUlZGNVEwdE9jRWRJUzNWaFZXb3dWbDk1WDNaemVWUldiRFJUVW5CUFpUWkRla3hqYzBsM0xXYzFVMk5STkRscGNERmxiVmxGTjI4MVJGVldZazlNUTBKNVdVUTFiamhEUWpOVE4xaHBkSFV3YUVORVMxOWtVM1ZUWmpSQlJreFVhalZ2VjNFMlpETnFlRFIzWkVwRlozbEVYM2R1TlVoSk1FZGxlbmg2Wldsb2RHOVdjVXh1WTNKS2JHUTVZVkZ6TFVKSFlrbHRXRk16UXpkM01rTkNjemMxUjBoT1l6UXdVa1JFUVZneFN6UnVObTVwZDAxTFpXRnRVbkJZTVZOR1dtMDVRVFJTUW1Rd2QyNUVYMHR6VDFsVUxUUjFTMGQwWkhGNGIwNXZUR2hUUkd0TlVrNXRNMEUwTFRoSVFreHhhMEpHYWkxcVMwRnpkRWxPZDFoV2IyaDJNR3gzYXpGSVNFOW1ZMXAyVDNKMmRUQXlXamMwUlZJMk9GODBlV3BNTWtwUFowdzNSVzVHZUVwdVYzaDRUR2RrVlZwM00xSm5hbTg1Y0ZkV2VXVXhRazlvV0hCdlREZzFRM0E0TW1nd1drSm5XRkZMV1RSTU0xOWFiREp1YTFBMmNYbFpNbHBFYkhCSWRHaFlhRFJ6Y1hBMGFYTkZkVGhSTnpjMlNYY3diVTQxZURGS2RrRnRlWHBZVlhCTGRVbzNTVTQxZWtWSmJGSnNWRWx0VlZNdFFrdHNTSGxvVTJKR1RtSlhkMEZvZDBaSk5uQjJlSEZZYTBKVWEyWkxjVlppYlZvelNIQlhWRzlYTURWeWFHWjZTVGsxTjBnMlpqSmxZVmxaWVdGb05sUnpibWxKVlU4NVNsSTJSV2xIZG5scmQzRkZWbkoxWVV4b1VsRnFRMUptUldSbVRGRlJRVkV5WW5oTlJFcG9kMlV5WW5wMlVsbHFNV2hmVWw5elVEaGZVWEYwYVhnMlNHOWhiRlpVT1ZKdVJXeGpSMlZFYm5seVVrTTJRa2hHZVdJeE1XcGhSbXBuTTBKS2JHUlpXak5NYWxaT01VUlFTekpoYWpCcU16VnRWeTEzYTNGVVQwRnJUV1I1ZDE5WFZFSXRWekJ0WVV0TmJFUm9VM1J5T1ZKcVZETlhVek5EVmtWRFRFdzBiMUpPTW1SMk1UUnlWRk41UkRscVNrUnhPSFJyTm1kb1gwUjJTV1ZKWm5Kd1NHdzFlRWs0UzJ4dWEyeEVjMnd0Y1VORWJEY3hVbEJCT0VoaE1pNWljbEk1YlROWk5WY3hRa0paU0ZOVlJrMW9ObmRSLmtCNjlONWZuMXdBQm9WU1JQMDcxTXdyeHJrSFpjSjViXzBCdzQxMHRYb0UiLCJleHAiOjE2ODczNTc3MzksImlhdCI6MTY4NzM1NzQzOX0.8QcUHytp7PWmxLWVVg6F3vxbnCGv_99m15LDXpsXjDE',
  callbacks: [
    {
      type: CallbackType.TextOutputCallback,
      output: [
        {
          name: 'message',
          value:
            '/*\n * Copyright 2018 ForgeRock AS. All Rights Reserved\n *\n * Use of this code requires a commercial software license with ForgeRock AS.\n * or with one of its affiliates. All use shall be exclusively subject\n * to such license between the licensee and ForgeRock AS.\n */\n\nvar newLocation = document.getElementById("wrapper");\nvar oldHtml = newLocation.getElementsByTagName("fieldset")[0].innerHTML;\nnewLocation.getElementsByTagName("fieldset")[0].innerHTML = "<div class=\\"panel panel-default\\">\\n" +\n    "    <div class=\\"panel-body text-center\\">\\n" +\n    "        <h3>Your Recovery Codes</h3>\\n" +\n    "        <h4>You must make a copy of these recovery codes. They cannot be displayed again.</h4>\\n" +\n    "    </div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "CyFrHnLq2x\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "x95uukzd3C\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "FHmdsD8khD\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "s77okhRxLX\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "XuTOVS00K6\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "CWmtqmR34b\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "N9v9L1ultI\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "ciA0MUvRRn\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "iVowPQpu7V\\n" +\n    "</div>\\n" +\n    "<div class=\\"text-center\\">\\n" +\n    "RsRY6CkwF3\\n" +\n    "</div>\\n" +\n    "<div class=\\"panel-body text-center\\">\\n" +\n    "        <p>Use one of these codes to authenticate if you lose your device, which has been named: <em>New Security Key</em></p>\\n" +\n    "</div>\\n" +\n    "</div>" + oldHtml;\ndocument.body.appendChild(newLocation);\n\n\n',
        },
        { name: 'messageType', value: '4' },
      ],
    },
  ],
};
export const usernamePasswordStep: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkxvZ2luIiwib3RrIjoiNmwxb2RmdWFzbjBxMXNrZXBjZTUzZmMyNCIsImF1dGhJbmRleFR5cGUiOiJzZXJ2aWNlIiwicmVhbG0iOiIvYWxwaGEiLCJzZXNzaW9uSWQiOiIqQUFKVFNRQUNNRElBQkhSNWNHVUFDRXBYVkY5QlZWUklBQUpUTVFBQ01ERS4qZXlKMGVYQWlPaUpLVjFRaUxDSmpkSGtpT2lKS1YxUWlMQ0poYkdjaU9pSklVekkxTmlKOS5aWGxLTUdWWVFXbFBhVXBMVmpGUmFVeERTbXhpYlUxcFQybEtRazFVU1RSUk1FcEVURlZvVkUxcVZUSkphWGRwV1ZkNGJrbHFiMmxhUjJ4NVNXNHdMaTVrTVhnMlptVkJNVmhZU0ZnNFR6VlNTMmRTUTFKQkxsQTBVV0p4Um10Tk5tMDRSblpNV1Y5eVZ6UnBZM0IzVlRneGIxUkxUa3c0YUVweE9UZFNOSGhHYzBGRVpIUjVRVlpMVVhab2Vtd3hjRkl6VVdsMGNIaENVV1pPVVhSbmFWODJlUzFmVGxCR1UwMVJkRGhNT0VSMGFVUk1UMkpHYUZsck1XSnNYMUUxU1ROQlRHd3dRbXRGVjI5TWNUaExTR001V21SbVpWTkZRVXBOTjBFMVEzQTBaRzQxVEc5cExTMVFUWGRoWnpaM2FrUkxORWxmVldKWllXbFRTak5FZGxkclQwZFpSVTV6V0hsSWFuY3RjV0o1WlV0emR6RTBZVWR6Ym5CdVVIVnNWbTFXWkZOc01XMUViSFUyTmxsNFZXOUhUMlZ3UVRKU09VSnVVRE5rYjBOWFMyTXpkREJqWXpVMWFqRm5lUzFYYzJabmVGTmlWekZZTlhkcVRtZFBVR1ozWW5SNVRISktjMHRwYzA0eWMyTTJWbFJ1T1RnMFZpMUVWVzVzVjJRMVN6QlZVVXBPY2w5MllVMURUMUZtU1hSM2NFc3lYMnhZWVhCdE9VVjNWRW8zY0VwVmQwVnJabHBKTkRWM1IyVlBVMGRDVlVaWlp5MVVhV05IVEdwT2NrcGZXazlxTkdKZmVXMWphWE5SU0U1WFdGOUtZeTFRZFZJNGIyWm9RbkE1U1RaRGMyWmZVbGcwWHpKUGJteDNVbDk0Y0d4dFUySlVSVlIxWTA5UVNHTnBkSGx1VjFsQ05VaDJObnB4WjFaNmJ5MDRNMkZCUVVzdFQydGpZWHBNWm1NeU1XYzNNbW94ZWxCU05HWnBhbUZaYVhGRFZGOUVhWE5IT0c0eVV6RkZUazF5T1ZOV2N6QmFjSE5WYkRKWlYzUkplSGhqT0MxMmMxQTBiaTEzWnpsUk5XcExkbkozWlV0c2EyOU9WazVETm5wT1dDMUNhbll6WVV0dFVUTjRVbVJxYUc5eU4zQnJSSFI2TUZKU1RHcHJXaTFYWkdwb05UaFliVFJtYTFKVFJFOTJWMHBLUlZJNVFUUmtXbEZHZEU1elQxcHBTR3BWWjFOdFgzVnpNSE4xZFVwR09EZE5hQzA0WldGd1YybDFMWGgzZFZaeGNuVk5SV0pQVmpGR1J6ZFJUbmRNU1RBdGJWWmlja3gyZVVsS04wNUJiamhxVEZZdFlsZHFMVVp1Wm1vd0xqWlBjemhUU2taUFNUaDRPVzgyTkV4NVdrNXVMVkUuRGpTUGdQck5VdFQ0U2JKWm9fZ2NiUlZCbWVQcGRHcUZzb1UyM250dVNCdyIsImV4cCI6MTY1NDIxNDQxMywiaWF0IjoxNjU0MjE0MTEzfQ.ZGwMWJb5crNXiAvvfvnwciOTyXaAKHjSk-aExg7QdnQ',
  callbacks: [
    {
      type: CallbackType.NameCallback,
      output: [{ name: 'prompt', value: 'User Name' }],
      input: [{ name: 'IDToken1', value: '' }],
      _id: 0,
    },
    {
      type: CallbackType.PasswordCallback,
      output: [{ name: 'prompt', value: 'Password' }],
      input: [{ name: 'IDToken2', value: '' }],
      _id: 1,
    },
  ],
  stage: 'DefaultLogin',
  header: 'Sign In',
  description:
    'New here? <a href="#/service/Registration">Create an account</a><br><a href="#/service/ForgottenUsername">Forgot username?</a><a href="#/service/ResetPassword"> Forgot password?</a>',
};

export const registrationStep: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlJlZ2lzdHJhdGlvbiIsIm90ayI6ImlnOXFqMWNrbjFkYnVjajE2dXBtYmlsYjZtIiwiYXV0aEluZGV4VHlwZSI6InNlcnZpY2UiLCJyZWFsbSI6Ii9hbHBoYSIsInNlc3Npb25JZCI6IipBQUpUU1FBQ01ESUFCSFI1Y0dVQUNFcFhWRjlCVlZSSUFBSlRNUUFDTURFLipleUowZVhBaU9pSktWMVFpTENKamRIa2lPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LlpYbEtNR1ZZUVdsUGFVcExWakZSYVV4RFNteGliVTFwVDJsS1FrMVVTVFJSTUVwRVRGVm9WRTFxVlRKSmFYZHBXVmQ0YmtscWIybGFSMng1U1c0d0xpNWpPRlJEUTJWRFkyaG9iR1l5ZVRkZmJDMDFSVXhSTGt3eUxWQlRSSFJzUldkVmIzUkZZV3RrZWpNMGQwSXlNekJDTTFGbVNGbGhhV2xZZGpFelV6RmxVWEl0UkcwNVRWY3dTR2htU3pKWk5WcGlPVlo2Yld0b2NFSjRiVGx5UXpFMVUyTmZaRTFSTm1oUk1rMTFOSFpsVm0xTlJUUTNTV3R1Y0djeU1sbE9lVUZRUzJKaGVucGpSMnRMVmxoVmJuWmpjVkpCU25KbGVGQkNRWGxLTURWZlNFdHdNMUIyWTBkaVlVOTRZMVJxVDFCWFQyRTRTbTF6UkRCbGFITk1XV1p3YzFOalIwMVdaVEZyYUU4dFJUZDZPR1YyVGxaVmNqUjNNRTgyVHpoS05GSTRkMHhwU3pseWJsTkpkVlpOZUU5RFFVbDZOVjh5UlhrdE5qazNabVUyTmtKek9UTm5ka3hUU1ZsWVYyVkZkVlF0Um1GRFJ6VTFWWGx5UWxSRGNUZzFTRE14TlZCSU5HMUVTRXhqU25GTWVIbElYM0pIV1RkcFpXRnhORUowV2xVM2RIbHJaVWhZYTBwUU5GVXhTRVJXUWs1M2MwMVhRME5QVUcxSVNGcHpRUzB0WkdkU1Jtb3pabkF3ZEZoWlgxSjRlR3hpUkdONU9WZHlZMG81VkROVWRrRlhSM2N3TTJoUlJISmZTMXBxY1d4bE1YRk5hWFp3TWpoemNHTnRURU5zWmtkYVZVdDZSRlIwTW5wamVqVlZkMVpEYnpsSU4zSmFhRVprZDJkM1lqQm5Ta2xsYTFKTWNXY3pRa3MzUzFCaFYwTnpNbTkxWVdrNExWUlBkM1J6VW14eGR6VTFRMjE0TVZGbFgzVnROVTFyY0dGUU9FSkJNRFUzTUVGNVpYQjNaVTFzVkRsd2FHTlJVSGhTY0Y5NU1FeHNRMkZIUWtOYWNqUmFYMVpqWlhGelIwMUlNbGR1YUdob1VXOTRhM2hNWkRkcFFWcEJNMjFqVlhWMFRtTnhRVlpOZFVwTFdsbHZPVkUxYm5oSk5IWnhWMEpKWkZWNk9IaFljR3BOVGpoR2EwSjVOVmMyY0V4M1lWQkVRaTF5V0dJNVlXeHljQzB0WWt0a2REVjZjRWxXWnpFelRFTjBhV1YzY1haSldFeFFZVEk1V2t0T2FVRjVTblJYWHpkV1gzTjRhbkpXWWxKMk5tMXdUM1ZRYW05dk4xWmZRbWRTWDFCaFZFbFBhR1ZxU0VwbVdtWlVPVjl3ZWw5T1kybFJTbFpFY0ZGTlRrMW9NRnBPZHpKT1dHdEVZMDh4VWtwb1pHNTFaRmRsVGxCc1psWk1NRGhHWm5CYWJFWlFZa3g1YVhsTU5USkZlVjl1ZVV0clIySnRTekEwWTFSaUxXRjNMVko0TVhCb2JqZEROMWhwYzA4elJWOVhYMmN1TTFZeldHNUNNbUZtZEV4NWRWUlVNME5aYldvemR3LmRKWUJVTk5Hb3h6WmZDNDZpQmp2c2VPcVNYVmJLcmNhcC11eko2cGl2ZmMiLCJleHAiOjE2NTQyMTM4ODgsImlhdCI6MTY1NDIxMzU4OH0.2TyyM5dBQYMfuOX24kIzwSy5GSGT8glabII8QN7Gl7A',
  callbacks: [
    {
      type: CallbackType.ValidatedCreateUsernameCallback,
      output: [
        {
          name: 'policies',
          value: {
            policyRequirements: [
              'REQUIRED',
              'MIN_LENGTH',
              'VALID_TYPE',
              'VALID_USERNAME',
              'CANNOT_CONTAIN_CHARACTERS',
              'MAX_LENGTH',
            ],
            fallbackPolicies: null,
            name: 'userName',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              { policyRequirements: ['REQUIRED'], policyId: 'not-empty' },
              {
                policyRequirements: ['MIN_LENGTH'],
                policyId: 'minimum-length',
                params: { minLength: 1 },
              },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
              { policyId: 'valid-username', policyRequirements: ['VALID_USERNAME'] },
              {
                policyId: 'cannot-contain-characters',
                params: { forbiddenChars: ['/'] },
                policyRequirements: ['CANNOT_CONTAIN_CHARACTERS'],
              },
              {
                policyId: 'minimum-length',
                params: { minLength: 1 },
                policyRequirements: ['MIN_LENGTH'],
              },
              {
                policyId: 'maximum-length',
                params: { maxLength: 255 },
                policyRequirements: ['MAX_LENGTH'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Username' },
      ],
      input: [
        { name: 'IDToken1', value: '' },
        { name: 'IDToken1validateOnly', value: false },
      ],
      _id: 0,
    },
    {
      type: CallbackType.StringAttributeInputCallback,
      output: [
        { name: 'name', value: 'givenName' },
        { name: 'prompt', value: 'First Name' },
        { name: 'required', value: true },
        {
          name: 'policies',
          value: {
            policyRequirements: ['REQUIRED', 'VALID_TYPE'],
            fallbackPolicies: null,
            name: 'givenName',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: '' },
      ],
      input: [
        { name: 'IDToken2', value: '' },
        { name: 'IDToken2validateOnly', value: false },
      ],
      _id: 1,
    },
    {
      type: CallbackType.StringAttributeInputCallback,
      output: [
        { name: 'name', value: 'sn' },
        { name: 'prompt', value: 'Last Name' },
        { name: 'required', value: true },
        {
          name: 'policies',
          value: {
            policyRequirements: ['REQUIRED', 'VALID_TYPE'],
            fallbackPolicies: null,
            name: 'sn',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: '' },
      ],
      input: [
        { name: 'IDToken3', value: '' },
        { name: 'IDToken3validateOnly', value: false },
      ],
      _id: 2,
    },
    {
      type: CallbackType.StringAttributeInputCallback,
      output: [
        { name: 'name', value: 'mail' },
        { name: 'prompt', value: 'Email Address' },
        { name: 'required', value: true },
        {
          name: 'policies',
          value: {
            policyRequirements: ['REQUIRED', 'VALID_TYPE', 'VALID_EMAIL_ADDRESS_FORMAT'],
            fallbackPolicies: null,
            name: 'mail',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
              {
                policyId: 'valid-email-address-format',
                policyRequirements: ['VALID_EMAIL_ADDRESS_FORMAT'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: '' },
      ],
      input: [
        { name: 'IDToken4', value: '' },
        { name: 'IDToken4validateOnly', value: false },
      ],
      _id: 3,
    },
    {
      type: CallbackType.BooleanAttributeInputCallback,
      output: [
        { name: 'name', value: 'preferences/marketing' },
        { name: 'prompt', value: 'Send me special offers and services' },
        { name: 'required', value: true },
        { name: 'policies', value: {} },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: false },
      ],
      input: [
        { name: 'IDToken5', value: false },
        { name: 'IDToken5validateOnly', value: false },
      ],
      _id: 4,
    },
    {
      type: CallbackType.ChoiceCallback,
      output: [
        {
          name: 'prompt',
          value: 'Choose one',
        },
        {
          name: 'choices',
          value: ['Choice A', 'Choice B', 'Choice C'],
        },
        {
          name: 'defaultChoice',
          value: 2,
        },
      ],
      input: [
        {
          name: 'IDToken1',
          value: 0,
        },
      ],
    },
    {
      type: CallbackType.ValidatedCreatePasswordCallback,
      output: [
        { name: 'echoOn', value: false },
        {
          name: 'policies',
          value: {
            policyRequirements: [
              'VALID_TYPE',
              'MIN_LENGTH',
              'AT_LEAST_X_CAPITAL_LETTERS',
              'AT_LEAST_X_NUMBERS',
              'CANNOT_CONTAIN_OTHERS',
            ],
            fallbackPolicies: null,
            name: 'password',
            policies: [
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: {
                  types: ['string'],
                },
              },
              {
                policyId: 'minimum-length',
                params: {
                  minLength: 8,
                },
                policyRequirements: ['MIN_LENGTH'],
              },
              {
                policyId: 'at-least-X-capitals',
                params: {
                  numCaps: 1,
                },
                policyRequirements: ['AT_LEAST_X_CAPITAL_LETTERS'],
              },
              {
                policyId: 'at-least-X-numbers',
                params: {
                  numNums: 1,
                },
                policyRequirements: ['AT_LEAST_X_NUMBERS'],
              },
              {
                policyId: 'cannot-contain-others',
                params: {
                  disallowedFields: ['userName', 'givenName', 'sn'],
                },
                policyRequirements: ['CANNOT_CONTAIN_OTHERS'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Password' },
      ],
      input: [
        { name: 'IDToken7', value: '' },
        { name: 'IDToken7validateOnly', value: false },
      ],
      _id: 6,
    },
    {
      type: CallbackType.KbaCreateCallback,
      output: [
        { name: 'prompt', value: 'Select a security question' },
        { name: 'predefinedQuestions', value: ["What's your favorite color?"] },
        {
          name: 'allowUserDefinedQuestions',
          value: true,
        },
      ],
      input: [
        { name: 'IDToken8question', value: '' },
        { name: 'IDToken8answer', value: '' },
      ],
      _id: 7,
    },
    {
      type: CallbackType.TermsAndConditionsCallback,
      output: [
        { name: 'version', value: '0.0' },
        {
          name: 'terms',
          value:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        },
        { name: 'createDate', value: '2019-10-28T04:20:11.320Z' },
      ],
      input: [{ name: 'IDToken9', value: false }],
      _id: 8,
    },
  ],
  stage: 'DefaultRegistration',
};

export const registrationStepWithTwoKBAs: Step = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlJlZ2lzdHJhdGlvbiIsIm90ayI6ImlnOXFqMWNrbjFkYnVjajE2dXBtYmlsYjZtIiwiYXV0aEluZGV4VHlwZSI6InNlcnZpY2UiLCJyZWFsbSI6Ii9hbHBoYSIsInNlc3Npb25JZCI6IipBQUpUU1FBQ01ESUFCSFI1Y0dVQUNFcFhWRjlCVlZSSUFBSlRNUUFDTURFLipleUowZVhBaU9pSktWMVFpTENKamRIa2lPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LlpYbEtNR1ZZUVdsUGFVcExWakZSYVV4RFNteGliVTFwVDJsS1FrMVVTVFJSTUVwRVRGVm9WRTFxVlRKSmFYZHBXVmQ0YmtscWIybGFSMng1U1c0d0xpNWpPRlJEUTJWRFkyaG9iR1l5ZVRkZmJDMDFSVXhSTGt3eUxWQlRSSFJzUldkVmIzUkZZV3RrZWpNMGQwSXlNekJDTTFGbVNGbGhhV2xZZGpFelV6RmxVWEl0UkcwNVRWY3dTR2htU3pKWk5WcGlPVlo2Yld0b2NFSjRiVGx5UXpFMVUyTmZaRTFSTm1oUk1rMTFOSFpsVm0xTlJUUTNTV3R1Y0djeU1sbE9lVUZRUzJKaGVucGpSMnRMVmxoVmJuWmpjVkpCU25KbGVGQkNRWGxLTURWZlNFdHdNMUIyWTBkaVlVOTRZMVJxVDFCWFQyRTRTbTF6UkRCbGFITk1XV1p3YzFOalIwMVdaVEZyYUU4dFJUZDZPR1YyVGxaVmNqUjNNRTgyVHpoS05GSTRkMHhwU3pseWJsTkpkVlpOZUU5RFFVbDZOVjh5UlhrdE5qazNabVUyTmtKek9UTm5ka3hUU1ZsWVYyVkZkVlF0Um1GRFJ6VTFWWGx5UWxSRGNUZzFTRE14TlZCSU5HMUVTRXhqU25GTWVIbElYM0pIV1RkcFpXRnhORUowV2xVM2RIbHJaVWhZYTBwUU5GVXhTRVJXUWs1M2MwMVhRME5QVUcxSVNGcHpRUzB0WkdkU1Jtb3pabkF3ZEZoWlgxSjRlR3hpUkdONU9WZHlZMG81VkROVWRrRlhSM2N3TTJoUlJISmZTMXBxY1d4bE1YRk5hWFp3TWpoemNHTnRURU5zWmtkYVZVdDZSRlIwTW5wamVqVlZkMVpEYnpsSU4zSmFhRVprZDJkM1lqQm5Ta2xsYTFKTWNXY3pRa3MzUzFCaFYwTnpNbTkxWVdrNExWUlBkM1J6VW14eGR6VTFRMjE0TVZGbFgzVnROVTFyY0dGUU9FSkJNRFUzTUVGNVpYQjNaVTFzVkRsd2FHTlJVSGhTY0Y5NU1FeHNRMkZIUWtOYWNqUmFYMVpqWlhGelIwMUlNbGR1YUdob1VXOTRhM2hNWkRkcFFWcEJNMjFqVlhWMFRtTnhRVlpOZFVwTFdsbHZPVkUxYm5oSk5IWnhWMEpKWkZWNk9IaFljR3BOVGpoR2EwSjVOVmMyY0V4M1lWQkVRaTF5V0dJNVlXeHljQzB0WWt0a2REVjZjRWxXWnpFelRFTjBhV1YzY1haSldFeFFZVEk1V2t0T2FVRjVTblJYWHpkV1gzTjRhbkpXWWxKMk5tMXdUM1ZRYW05dk4xWmZRbWRTWDFCaFZFbFBhR1ZxU0VwbVdtWlVPVjl3ZWw5T1kybFJTbFpFY0ZGTlRrMW9NRnBPZHpKT1dHdEVZMDh4VWtwb1pHNTFaRmRsVGxCc1psWk1NRGhHWm5CYWJFWlFZa3g1YVhsTU5USkZlVjl1ZVV0clIySnRTekEwWTFSaUxXRjNMVko0TVhCb2JqZEROMWhwYzA4elJWOVhYMmN1TTFZeldHNUNNbUZtZEV4NWRWUlVNME5aYldvemR3LmRKWUJVTk5Hb3h6WmZDNDZpQmp2c2VPcVNYVmJLcmNhcC11eko2cGl2ZmMiLCJleHAiOjE2NTQyMTM4ODgsImlhdCI6MTY1NDIxMzU4OH0.2TyyM5dBQYMfuOX24kIzwSy5GSGT8glabII8QN7Gl7A',
  callbacks: [
    {
      type: CallbackType.ValidatedCreateUsernameCallback,
      output: [
        {
          name: 'policies',
          value: {
            policyRequirements: [
              'REQUIRED',
              'MIN_LENGTH',
              'VALID_TYPE',
              'VALID_USERNAME',
              'CANNOT_CONTAIN_CHARACTERS',
              'MAX_LENGTH',
            ],
            fallbackPolicies: null,
            name: 'userName',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              { policyRequirements: ['REQUIRED'], policyId: 'not-empty' },
              {
                policyRequirements: ['MIN_LENGTH'],
                policyId: 'minimum-length',
                params: { minLength: 1 },
              },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
              { policyId: 'valid-username', policyRequirements: ['VALID_USERNAME'] },
              {
                policyId: 'cannot-contain-characters',
                params: { forbiddenChars: ['/'] },
                policyRequirements: ['CANNOT_CONTAIN_CHARACTERS'],
              },
              {
                policyId: 'minimum-length',
                params: { minLength: 1 },
                policyRequirements: ['MIN_LENGTH'],
              },
              {
                policyId: 'maximum-length',
                params: { maxLength: 255 },
                policyRequirements: ['MAX_LENGTH'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Username' },
      ],
      input: [
        { name: 'IDToken1', value: '' },
        { name: 'IDToken1validateOnly', value: false },
      ],
      _id: 0,
    },
    {
      type: CallbackType.StringAttributeInputCallback,
      output: [
        { name: 'name', value: 'mail' },
        { name: 'prompt', value: 'Email Address' },
        { name: 'required', value: true },
        {
          name: 'policies',
          value: {
            policyRequirements: ['REQUIRED', 'VALID_TYPE', 'VALID_EMAIL_ADDRESS_FORMAT'],
            fallbackPolicies: null,
            name: 'mail',
            policies: [
              { policyRequirements: ['REQUIRED'], policyId: 'required' },
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: { types: ['string'] },
              },
              {
                policyId: 'valid-email-address-format',
                policyRequirements: ['VALID_EMAIL_ADDRESS_FORMAT'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: '' },
      ],
      input: [
        { name: 'IDToken4', value: '' },
        { name: 'IDToken4validateOnly', value: false },
      ],
      _id: 3,
    },
    {
      type: CallbackType.BooleanAttributeInputCallback,
      output: [
        { name: 'name', value: 'preferences/marketing' },
        { name: 'prompt', value: 'Send me special offers and services' },
        { name: 'required', value: true },
        { name: 'policies', value: {} },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'value', value: false },
      ],
      input: [
        { name: 'IDToken5', value: false },
        { name: 'IDToken5validateOnly', value: false },
      ],
      _id: 4,
    },
    {
      type: CallbackType.ChoiceCallback,
      output: [
        {
          name: 'prompt',
          value: 'Choose one',
        },
        {
          name: 'choices',
          value: ['Choice A', 'Choice B', 'Choice C'],
        },
        {
          name: 'defaultChoice',
          value: 2,
        },
      ],
      input: [
        {
          name: 'IDToken1',
          value: 0,
        },
      ],
    },
    {
      type: CallbackType.ValidatedCreatePasswordCallback,
      output: [
        { name: 'echoOn', value: false },
        {
          name: 'policies',
          value: {
            policyRequirements: [
              'VALID_TYPE',
              'MIN_LENGTH',
              'AT_LEAST_X_CAPITAL_LETTERS',
              'AT_LEAST_X_NUMBERS',
              'CANNOT_CONTAIN_OTHERS',
            ],
            fallbackPolicies: null,
            name: 'password',
            policies: [
              {
                policyRequirements: ['VALID_TYPE'],
                policyId: 'valid-type',
                params: {
                  types: ['string'],
                },
              },
              {
                policyId: 'minimum-length',
                params: {
                  minLength: 8,
                },
                policyRequirements: ['MIN_LENGTH'],
              },
              {
                policyId: 'at-least-X-capitals',
                params: {
                  numCaps: 1,
                },
                policyRequirements: ['AT_LEAST_X_CAPITAL_LETTERS'],
              },
              {
                policyId: 'at-least-X-numbers',
                params: {
                  numNums: 1,
                },
                policyRequirements: ['AT_LEAST_X_NUMBERS'],
              },
              {
                policyId: 'cannot-contain-others',
                params: {
                  disallowedFields: ['userName', 'givenName', 'sn'],
                },
                policyRequirements: ['CANNOT_CONTAIN_OTHERS'],
              },
            ],
            conditionalPolicies: null,
          },
        },
        { name: 'failedPolicies', value: [] },
        { name: 'validateOnly', value: false },
        { name: 'prompt', value: 'Password' },
      ],
      input: [
        { name: 'IDToken7', value: '' },
        { name: 'IDToken7validateOnly', value: false },
      ],
      _id: 6,
    },
    {
      type: CallbackType.KbaCreateCallback,
      output: [
        { name: 'prompt', value: 'Select a security question' },
        {
          name: 'predefinedQuestions',
          value: ["What's your favorite color?", 'Where did you grow up?'],
        },
        {
          name: 'allowUserDefinedQuestions',
          value: true,
        },
      ],
      input: [
        { name: 'IDToken8question', value: '' },
        { name: 'IDToken8answer', value: '' },
      ],
      _id: 7,
    },
    {
      type: CallbackType.KbaCreateCallback,
      output: [
        {
          name: 'prompt',
          value: 'Select second question',
        },
        {
          name: 'predefinedQuestions',
          value: ["What's your favorite color?", 'Where did you grow up?'],
        },
        {
          name: 'allowUserDefinedQuestions',
          value: true,
        },
      ],
      input: [
        {
          name: 'IDToken9question',
          value: '',
        },
        {
          name: 'IDToken9answer',
          value: '',
        },
      ],
      _id: 8,
    },
    {
      type: CallbackType.TermsAndConditionsCallback,
      output: [
        { name: 'version', value: '0.0' },
        {
          name: 'terms',
          value:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        },
        { name: 'createDate', value: '2019-10-28T04:20:11.320Z' },
      ],
      input: [{ name: 'IDToken9', value: false }],
      _id: 8,
    },
  ],
  stage: 'DefaultRegistration',
};

export const webAuthnAuthenticationStep = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlBhc3N3b3JkbGVzc1dlYkF1dGhuIiwib3RrIjoiOGdpaDJxdHJhNzltZTgwa3ZqZGg0MTlkbTUiLCJhdXRoSW5kZXhUeXBlIjoic2VydmljZSIsInJlYWxtIjoiL2FscGhhIiwic2Vzc2lvbklkIjoiKkFBSlRTUUFDTURJQUJIUjVjR1VBQ0VwWFZGOUJWVlJJQUFKVE1RQUNNREUuKmV5SjBlWEFpT2lKS1YxUWlMQ0pqZEhraU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYVhkcFdWZDRia2xxYjJsYVIyeDVTVzR3TGk1TWJsQkxWR2h4V2tab1ZUTkhUa1IyVVdwRmR6RlJMbUV0ZG5GSVIyMDRlakZKYlV4WWRFZHljbTEwY0dST2FtWnJSalV3ZW01cmFYb3pjV1EzYldOV1ZURnRNVUp3YkhwR1ZGVk1kRzh6TFRaeVJrdHBTMnBSUW5ST2FITTRWMlJzVjI5d1gxZzNjVTk2WjJKYVpWYzVMV1kzVmtFdFZESkxVM0pTTkhoR1VHZElWV3hJYlZGYWFGaDNSRWd5VUZseFZuaHJRV1pUY1RGWVlXUlBSSHBDZVZWUGRuRk5ibWR5VEdJelpEQm9SMjVZWWtSUVFqTktibGxDWmtneWFEQlJURzl6TkdKV1drMUliRzlFVjNGd05HeDZWV0puZGtaVVJuTnVkR1JoUkRaaGJrUTBTbVYyVDJKME5YZGhVbUZrTmtST2QzTkxkMGREY0VwS1JYRTVNM0kwZEZrNGVqaGZXbUV6TVVsSmFGSXRNR0ZNVW5OeFNYSmFPVlZ0TlRFME4wVkpRVEkzWTFORmVGWTRTRmxtU1RFMmJpMWpjVEZ3YzNob1duQkhURWhWTjFONlRXODRSVzVITWxRMVMweGxSVm80VUZSWFUxQlZRMko2ZHpJMVMyTklRbEZsUWw5blVXTjFkMGRZVGtWdWFsVllNVjg1VGpkcFRXNDBabmw1ZERBNVVVVmlXVzg0VlRSMVNqSnpMV05OVmtaaldubENRbmx0YUU5bGJEaFRObU5FVUdSSVJIWlBTVE5aY0RKcWVtNTJVSEJpVmxBMlpVNXBla2Q2V0ROYVdrUnJWMU5JUkdNMFEwZHZWamh4TFdGeFNHWXllWE5LZGtwSWFHUk5hWFpLYlc1Zk1HWnBRa2hhWnpobk1HeGpWVzAxV21Jek5Wb3liVkJCV1UxUE5VaDFOVUpGT1Zab2N6QlhOelpvYUU1V2VraFBVMGszVmtKSFJ6bHRRMnRYY3kwNFNqUTRTVnBaWVc5aVZuaHhRbTFEV0ZSb05WTnpUV2RUTnpReU1qbGZUME5NVDJ0clJWY3dOWEpoTjIxUGJVeHpSR1JKVERONFVrNTVVREoxYkdOclFqUmFkelEzUzFGclZpMXpVMWRYWWtsblUxRmpWVmRUWlUxTGFuUmhPRkJCVUVOR1JFNW5TM0ZSU0ZJM2RtVnllRVIxZDNaTVp6QkNSbFZMYm1OZlQyUjJRazlFZHpFNVpEbHBRMWs1VHpSRVR6bEROR2RrWm1WeGNWWkZka1V0UmxacVRYTXRka1IxU2s4MlEyVkpiRGxOYm1keE4zZDRSM1JqT1VWNlMyUjNaVWRDT0dRMWVFeGlkazlsUzI1SlUyc3RhamRIVmpOdmRqQnFjREZhTWsxSU1rbzBUaTFsU0dwVVRDMURUV1JhU2k1MllUbDJRMjlLVmtrME1HVmlObkJSVEU1RmMxSlIuRFRJVUdaRnlrVUd2STlROVVvbFc1ZElMTWU3YUx2UFVZQVJzS3dUMy15dyIsImV4cCI6MTY4NzM3NTU2NCwiaWF0IjoxNjg3Mzc1MjY0fQ.dizHBQ9lBW36ZuOdvOH3rwE83zBcXNtHIjjYAIdFLmU',
  callbacks: [
    {
      type: 'MetadataCallback',
      output: [
        {
          name: 'data',
          value: {
            _action: 'webauthn_authentication',
            challenge: 'gNO22N2EuBw1eL9JXOZ0zZjflAQwtGLsMW4nFZJOl1E=',
            allowCredentials:
              'allowCredentials: [{ "type": "public-key", "id": new Int8Array([101, 22, 32, -44, 119, -77, 35, 104, -122, -104, 41, -78, 76, -61, -32, 46, 93, 16, -39, 55, 57, -97, 67, 44, 113, 54, -113, -94, -26, 38, -62, -29, -27, 83, -93, -96, -9, 25, -108, -38, -70, 37, 125, -7, -118, -37, -10, 52, -67, 41, -116, -44, 46, -116, 119, 117, 113, -24, 67, -12, 76, 30, -13, -44]).buffer }]',
            _allowCredentials: [
              {
                type: 'public-key',
                id: [
                  101, 22, 32, -44, 119, -77, 35, 104, -122, -104, 41, -78, 76, -61, -32, 46, 93,
                  16, -39, 55, 57, -97, 67, 44, 113, 54, -113, -94, -26, 38, -62, -29, -27, 83, -93,
                  -96, -9, 25, -108, -38, -70, 37, 125, -7, -118, -37, -10, 52, -67, 41, -116, -44,
                  46, -116, 119, 117, 113, -24, 67, -12, 76, 30, -13, -44,
                ],
              },
            ],
            timeout: '60000',
            userVerification: 'discouraged',
            relyingPartyId: '',
            _relyingPartyId: '',
            _type: 'WebAuthn',
          },
        },
      ],
    },
    {
      type: 'HiddenValueCallback',
      output: [
        { name: 'value', value: 'false' },
        { name: 'id', value: 'webAuthnOutcome' },
      ],
      input: [{ name: 'IDToken2', value: 'webAuthnOutcome' }],
    },
  ],
};

export const webAuthnRegistrationStep = {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IlBhc3N3b3JkbGVzc1dlYkF1dGhuIiwib3RrIjoidGljM3RrYTU3NTE3azM2bnE3NjA3OWw2bjUiLCJhdXRoSW5kZXhUeXBlIjoic2VydmljZSIsInJlYWxtIjoiL2FscGhhIiwic2Vzc2lvbklkIjoiKkFBSlRTUUFDTURJQUJIUjVjR1VBQ0VwWFZGOUJWVlJJQUFKVE1RQUNNREUuKmV5SjBlWEFpT2lKS1YxUWlMQ0pqZEhraU9pSktWMVFpTENKaGJHY2lPaUpJVXpJMU5pSjkuWlhsS01HVllRV2xQYVVwTFZqRlJhVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYVhkcFdWZDRia2xxYjJsYVIyeDVTVzR3TGk1bVZFaHViRTlWVjNGa0xVVkpZWHBNU25GNlJXTlJMa2hpWmpjdFMydFJkbWQzT1VSUlZUUk9UazkyYVZKUGRpMXllVm80TUVSd1lVVldUWFppT1RnNFJGOUdRekIzVjJwdlgwOTFjV1J3Y1ZGRFlXZEdWazl3ZW5OamJYbG9jekp0UTNkMExYbElORGRCYmpCR2IxQTNMWE5tYmtGMVZHZHRTWFpTUTBOV1UwRjFkVzVrZUdSWGJtaDVOMGN6YmtSRFIybEpUMEkzYWtSUWRYaFphMVUzUmtaWUxYSTFXa0pUZUVrNE9HOVdibGw0YW5GbGRXTTFOR3htV1RablRXMHhWMHBwU0hwVlkzbzBSakpCZG10NFEwbERSa1ppZEhoek5VaHBNMDV2WVhjd2VFRlRZVWcxWVhwdlNrbEJWVWRUTVdSMGVUbEJUMU15YVRSelRVVkNRa3B0U0V0UmRqbDBaalJ6TFZWamJFVkdWMEZ5WlRjeVJXOHplRWt3ZW5KWmVrSXhaR2hpVmpsRVlVbGlUbmN5WW5kNVUwRnZZemc1YTFGa2VEWmxWVU5yVTI5ak1FOXdWMHR3YldSTlJGazNVMlZvU1VwaGFXWk5iVW8wVnpCSVR6Vkdaa2hFTlVKeFEwMUJPVEZPYTNKNk4zcEtMVnBvYVVoalVEY3hUMjVzVkVSNE1YWlpTM294TkdoTlZHWnhhbEYxYTFKTE5HRTNWSEpYYWxGTE0zZG5aREV6TWpWT1lrNW9OV2t0WkhGUlVpMHlWbVpIWDJkbFFVOVBPRWt3V0hGWGFYTmtNMmhJWkVoU2IwTkthMjlKWW5JMWQzQmtPVXhXWTNCYU1tcG9TRjlsUmtaQ2VEQnBUemhqUVd0a1V6UTROMWR2UkdkUU1YbFROMXB5YTNacFgzb3dNME54ZDNWSVJYaEtSVGMxTTNNMFkwaEpUVzFKVFVreVpIbzFjamRDVGpBeldDMDRaSFIxYUZadVoyUldUSGxwVlVveFdubHBTMjV4U2kxVlpqbFVWemxVYTJWWVlUZENkM2h1ZGs1S09HVlNOMk5JY3pKRVJ6RmtWazFRWm5nNFJTMVpTbmhuUkZwUFdHRTNOM2RtZGpOcFdUWnZRbFU0YmxGcVZYTXRabVozWWpoaVdUUndibFl4VWxSdVdqaFFRbU5KUTB4NFVuTkpOWE5PWHpOU2NFRmtkbE5oYzJVd1NrZEdObUV4VGs5bVNHOU1haTFQU0VGTGN6WjFiVzFQVm1jMmVFUTNjVjlqYnkxYVVscENiRVJ2ZFVsdFJFVk5jMUJJTVdkVFRtRmliR042WkZKblZrWnNlbXhXYURac05sVk5kRnBsTFdSS2NXOXhWamxUVkdGVGVUbHZNMDlQT1U1SGEwbHBOVlppWDFOV04wNHlaVXRYUTJkVWNWcEtiVU5NTVdGMmFISndha0ZZUzNsNExWRnJMVlZEVDBRMk5sazBWMVpaWkVjNFdWWk9TbE01WlhwV01FUTJPVXBPY0ZWMlluVklXbE5EUkdkcGRqQjFaV2MzTUdsblVHeDVTMlY2VDJsNFRYQjJORUoyZUZaMGRFaDBUWFpwUm01R2RWbE9TVTFLVFVGTlZrOHpNR1ppV25Vd0xuUnBhall0WjBGdWRFYzVhemQzVnpCMVZrOHlVVkUuUzFwTGZ2cXdPXzVpTm10aE5ER0lxWVl6S1JjYXZEendIbzlqTEdSZFA0dyIsImV4cCI6MTY4NzM3NTczOSwiaWF0IjoxNjg3Mzc1NDM5fQ.CH0CHzW0Xk82ncr53x6n2MeHhK539VVCqHjpyn39uc0',
  callbacks: [
    {
      type: 'TextOutputCallback',
      output: [
        {
          name: 'message',
          value:
            '/*\n * Copyright 2018-2020 ForgeRock AS. All Rights Reserved\n *\n * Use of this code requires a commercial software license with ForgeRock AS.\n * or with one of its affiliates. All use shall be exclusively subject\n * to such license between the licensee and ForgeRock AS.\n */\n\nif (!window.PublicKeyCredential) {\n    document.getElementById(\'webAuthnOutcome\').value = "unsupported";\n    document.getElementById("loginButton_0").click();\n}\n\nvar publicKey = {\n    challenge: new Int8Array([-9, 108, -90, 2, 110, 98, -76, -65, -1, 93, 24, 82, -58, 109, 92, 24, 8, 87, -78, 83, -55, 42, -58, 73, -21, -22, 35, -109, 46, -2, -97, -78]).buffer,\n    // Relying Party:\n    rp: {\n        \n        name: "ForgeRock"\n    },\n    // User:\n    user: {\n        id: Uint8Array.from("NmNlNjdlNzYtYWVjYi00YjA1LWEzY2EtNGIzZjRlYTk3NDNk", function (c) { return c.charCodeAt(0) }),\n        name: "6ce67e76-aecb-4b05-a3ca-4b3f4ea9743d",\n        displayName: "6ce67e76-aecb-4b05-a3ca-4b3f4ea9743d"\n    },\n    pubKeyCredParams: [ { "type": "public-key", "alg": -7 }, { "type": "public-key", "alg": -257 } ],\n    attestation: "none",\n    timeout: 60000,\n    excludeCredentials: [],\n    authenticatorSelection: {"userVerification":"discouraged"}\n};\n\nnavigator.credentials.create({publicKey: publicKey})\n    .then(function (newCredentialInfo) {\n        var rawId = newCredentialInfo.id;\n        var clientData = String.fromCharCode.apply(null, new Uint8Array(newCredentialInfo.response.clientDataJSON));\n        var keyData = new Int8Array(newCredentialInfo.response.attestationObject).toString();\n        document.getElementById(\'webAuthnOutcome\').value = clientData + "::" + keyData + "::" + rawId;\n        document.getElementById("loginButton_0").click();\n    }).catch(function (err) {\n        document.getElementById(\'webAuthnOutcome\').value = "ERROR" + "::" + err;\n        document.getElementById("loginButton_0").click();\n    });',
        },
        { name: 'messageType', value: '4' },
      ],
    },
    {
      type: 'TextOutputCallback',
      output: [
        {
          name: 'message',
          value:
            '/*\n * Copyright 2018 ForgeRock AS. All Rights Reserved\n *\n * Use of this code requires a commercial software license with ForgeRock AS.\n * or with one of its affiliates. All use shall be exclusively subject\n * to such license between the licensee and ForgeRock AS.\n *\n */\n\n/*\n * Note:\n *\n * When a ConfirmationCallback is used (e.g. during recovery code use), the XUI does not render a loginButton. However\n * the webAuthn script needs to call loginButton.click() to execute the appropriate data reformatting prior to sending\n * the request into AM. Here we query whether the loginButton exists and add it to the DOM if it doesn\'t.\n */\n\nvar newLocation = document.getElementById("wrapper");\n\nvar script = "<div class=\\"form-group\\">\\n" +\n    "<div class=\\"panel panel-default\\">\\n" +\n    "    <div class=\\"panel-body text-center\\">\\n" +\n    "    <h4 class=\\"awaiting-response\\"><i class=\\"fa fa-circle-o-notch fa-spin text-primary\\"></i> Waiting for local device... </h4>\\n" +\n    "    </div>\\n" +\n    "</div>\\n";\n\nif (!document.getElementById("loginButton_0")) {\n    script += "<input id=\\"loginButton_0\\" role=\\"button\\" type=\\"submit\\" hidden>";\n} else {\n    document.getElementById("loginButton_0").style.visibility=\'hidden\';\n}\n\nscript += "</div>";\n\nnewLocation.getElementsByTagName("fieldset")[0].innerHTML += script;\ndocument.body.appendChild(newLocation);',
        },
        { name: 'messageType', value: '4' },
      ],
    },
    {
      type: 'HiddenValueCallback',
      output: [
        { name: 'value', value: 'false' },
        { name: 'id', value: 'webAuthnOutcome' },
      ],
      input: [{ name: 'IDToken3', value: 'webAuthnOutcome' }],
    },
  ],
};
