import fs from "node:fs";
import path from "node:path";

export interface ComponentMetadata {
  readonly type: "callback" | "stage";
  readonly name: string;
}

export interface DiscoveredComponent extends ComponentMetadata {
  readonly relativePath: string;
}

export function parseComponentMetadata(
  source: string,
): ComponentMetadata | null {
  const match = source.match(
    /<!--\s*@component\s+Type:\s*(callback|stage)\s+Name:\s*(\w+)\s*-->/s,
  );
  if (!match) return null;
  return { type: match[1] as "callback" | "stage", name: match[2] };
}

export function scanUserDirectory(userDir: string): DiscoveredComponent[] {
  const components: DiscoveredComponent[] = [];

  for (const componentType of ["stage", "callback"] as const) {
    const typeDir = path.join(userDir, componentType);
    if (!fs.existsSync(typeDir)) continue;

    for (const entry of fs.readdirSync(typeDir)) {
      const componentFile = path.join(typeDir, entry, "component.svelte");
      if (!fs.existsSync(componentFile)) continue;

      const source = fs.readFileSync(componentFile, "utf-8");
      const metadata = parseComponentMetadata(source);
      if (!metadata) continue;

      components.push({
        ...metadata,
        relativePath: `${componentType}/${entry}/component.svelte`,
      });
    }
  }

  return components;
}

export function generateRegistrySource(
  components: DiscoveredComponent[],
): string {
  const stages = components.filter((c) => c.type === "stage");
  const callbacks = components.filter((c) => c.type === "callback");

  const lines: string[] = [
    "// AUTO-GENERATED by ping-law CLI — do not edit manually",
    "// Re-run `ping-law scan` to regenerate",
    "",
  ];

  for (const component of [...stages, ...callbacks]) {
    lines.push(
      `import ${component.name} from "$user/${component.relativePath}";`,
    );
  }

  if (components.length > 0) lines.push("");

  if (stages.length === 0) {
    lines.push(
      "export const customStages = {} as Record<string, unknown>;",
    );
  } else {
    lines.push("export const customStages = {");
    for (const stage of stages) {
      lines.push(`  "${stage.name}": ${stage.name},`);
    }
    lines.push("} as Record<string, unknown>;");
  }

  lines.push("");

  if (callbacks.length === 0) {
    lines.push(
      "export const customCallbacks = {} as Record<string, unknown>;",
    );
  } else {
    lines.push("export const customCallbacks = {");
    for (const cb of callbacks) {
      lines.push(`  "${cb.name}": ${cb.name},`);
    }
    lines.push("} as Record<string, unknown>;");
  }

  lines.push("");
  return lines.join("\n");
}
