/**
 *
 * Copyright © 2025 - 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 **/

import { oidc } from '@forgerock/oidc-client';
import { writable } from 'svelte/store';
import { z } from 'zod';

import type { GetTokensOptions, OauthTokens, OidcClient } from '@forgerock/oidc-client/types';
import type { Writable } from 'svelte/store';

import type { Maybe } from '$core/interfaces';

const authorizationTimedOut = 'Authorization timed out';
const interactionNeeded = 'The request requires some interaction that is not allowed.';
const timeoutErrorMessage =
  'Timeouts are likely an issue with OAuth client misconfiguration. If you are getting a 4xx error in the network tab, copy the full `/authorize` URL and paste it directly into your browsers URL field to directly visit the page. The error should be displayed on the page.';
const sessionCookieConsentMessage = `The user either doesn't have a valid session, the cookie is not being sent due to third-party cookies being disabled, or the user is needing to provide consent as the OAuth client setting does not have "implied consent" enabled.`;

/**
 * The narrowed, ready-to-use OIDC client (the success branch of the `oidc()` factory union).
 * Exported so `user.store.ts` can type its injected `getOidcClient` parameter without
 * importing the underlying SDK type directly.
 */
export type OidcClientReady = Extract<OidcClient, { token: object }>;

/**
 * Configure the OIDC Client.
 */
export const oidcClientConfigSchema = z
  .object({
    clientId: z.string(),
    redirectUri: z.string().url({
      message: '`redirectUri` must be a full URL (this is generated by the Zod library).',
    }),
    scope: z.string().default('openid'),
    serverConfig: z
      .object({
        wellknown: z
          .string({
            error: (issue) =>
              issue.input === undefined
                ? 'Setting the `serverConfig.wellknown` is required (this is generated by the Zod library).'
                : '`serverConfig.wellknown` must be a URL string (this is generated by the Zod library).',
          })
          .url({
            message:
              '`serverConfig.wellknown` must be a full URL (this is generated by the Zod library).',
          }),
      })
      .strict(),
  })
  .strict();

export type OidcClientConfig = z.infer<typeof oidcClientConfigSchema>;

export interface OAuthStore extends Pick<Writable<OAuthTokenStoreValue>, 'subscribe'> {
  getTokens: (getOptions?: GetTokensOptions) => void;
  getOidcClient: () => Promise<OidcClientReady>;
  reset: () => void;
}
export interface OAuthTokenStoreValue {
  completed: boolean;
  error: Maybe<{
    code?: Maybe<number>;
    message: Maybe<string>;
    troubleshoot: Maybe<string>;
  }>;
  loading: boolean;
  successful: boolean;
  response: Maybe<OauthTokens> | void;
}

function getTroubleshootingMessage(message: Maybe<string>) {
  switch (message) {
    case interactionNeeded:
      return sessionCookieConsentMessage;
    case authorizationTimedOut:
      return timeoutErrorMessage;
    default:
      return '';
  }
}

/**
 * @function initialize - Creates a fresh, isolated OAuth store instance.
 *
 * All state (client config, client promise, store writable) lives inside this
 * closure — nothing is shared at module scope. Each call returns an independent
 * instance, so multiple widget instances or test runs cannot interfere with
 * each other.
 *
 * @param {OidcClientConfig} [config] - Optional OIDC client configuration. When omitted,
 *   `getOidcClient()` will throw (lazily) if called.
 * @param {GetTokensOptions} [initOptions] - Default options forwarded to `token.get`.
 */
export function initialize(config?: OidcClientConfig, initOptions?: GetTokensOptions): OAuthStore {
  // Closure-scoped: isolated per initialize() call, not shared across callers.
  const parsedConfig = config ? oidcClientConfigSchema.parse(config) : undefined;
  let oidcClientPromise: Promise<OidcClientReady> | undefined;
  const oauthStore = writable<OAuthTokenStoreValue>({
    completed: false,
    error: null,
    loading: false,
    successful: false,
    response: null,
  });

  /**
   * Returns a cached, ready-to-use OIDC client promise.
   * Exposed on the returned store so `user.store` and `widget.api` can inject it
   * without reaching back into module scope.
   */
  async function getOidcClient(): Promise<OidcClientReady> {
    if (!parsedConfig) {
      throw new Error('OIDC Client is not configured.');
    }
    if (!oidcClientPromise) {
      oidcClientPromise = (async () => {
        const client = await oidc({ config: parsedConfig });
        // The factory resolves to an error shape when initialization fails.
        if (client.error) {
          throw new Error(client.error);
        }
        return client as OidcClientReady;
      })().catch((err) => {
        // Clear the cache on failure so the next call can retry.
        oidcClientPromise = undefined;
        throw err;
      });
    }
    return oidcClientPromise;
  }

  async function getTokens(getOptions?: GetTokensOptions) {
    const options = {
      // https://github.com/ForgeRock/ping-javascript-sdk/blob/@forgerock/oidc-client@2.1.0/packages/oidc-client/src/lib/client.store.ts#L315-L322
      // https://github.com/ForgeRock/ping-javascript-sdk/blob/@forgerock/oidc-client@2.1.0/packages/oidc-client/src/lib/authorize.request.micros.ts#L122
      // backgroundRenew must be true or token.get() returns an error instead of fetching new tokens.
      // prompt=none is injected automatically by authorize.request.micros.ts — no need to set it via authorizeOptions.
      backgroundRenew: true,
      ...initOptions,
      ...getOptions,
    };

    oauthStore.set({
      completed: false,
      error: null,
      loading: true,
      successful: false,
      response: null,
    });

    try {
      const oidcClient = await getOidcClient();
      const tokens = await oidcClient.token.get(options);

      if ('error' in tokens) {
        const message =
          ('message' in tokens && tokens.message) ||
          ('error_description' in tokens && tokens.error_description) ||
          tokens.error;
        const code = 'code' in tokens && typeof tokens.code === 'number' ? tokens.code : null;
        oauthStore.set({
          completed: true,
          error: { code, message, troubleshoot: getTroubleshootingMessage(message) },
          loading: false,
          successful: false,
          response: null,
        });
        return;
      }

      oauthStore.set({
        completed: true,
        error: null,
        loading: false,
        successful: true,
        response: tokens,
      });
    } catch (err: unknown) {
      // Always an Error in practice; fallback covers unexpected third-party throws.
      const message = err instanceof Error ? err.message : 'Unknown OAuth error';
      oauthStore.set({
        completed: true,
        error: { message, troubleshoot: getTroubleshootingMessage(message) },
        loading: false,
        successful: false,
        response: null,
      });
    }
  }

  function reset() {
    oauthStore.set({
      completed: false,
      error: null,
      loading: false,
      successful: false,
      response: null,
    });
  }

  return {
    getTokens,
    getOidcClient,
    reset,
    subscribe: oauthStore.subscribe,
  };
}
