/**
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 **/

import { z } from 'zod';
import type { JourneyClient, JourneyClientConfig } from '@forgerock/journey-client/types';
import { journey } from '@forgerock/journey-client';

/**
 * Configure Journey Client
 */

const wellknownSchema = z
  .string({
    invalid_type_error:
      '`serverConfig.wellknown` must be a URL string (this is generated by the Zod library).',
    required_error:
      'Setting the `serverConfig.wellknown` is required (this is generated by the Zod library).',
  })
  .url({
    message: '`serverConfig.wellknown` must be a full URL (this is generated by the Zod library).',
  });

export const journeyClientConfigSchema: z.ZodType<JourneyClientConfig> = z
  .object({
    serverConfig: z
      .object({
        wellknown: wellknownSchema,
      })
      .strict(),
  })
  .strict();

let config: JourneyClientConfig | undefined;

export function setJourneyClientConfig(
  journeyClientConfig: JourneyClientConfig,
): JourneyClientConfig {
  config = journeyClientConfigSchema.parse(journeyClientConfig);
  return config;
}

export async function getJourneyClient(): Promise<JourneyClient> {
  if (!config) {
    throw new Error('Journey Client is not configured. Call setJourneyClientConfig() first.');
  }
  return await journey({ config });
}
