/**
 *
 * Copyright © 2025 - 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 **/

import { Config } from '@forgerock/javascript-sdk';
import { z } from 'zod';

import type { CallbackType, FRCallback } from '@forgerock/javascript-sdk';

type CallbackFactoryFn = (callback: {
  _id?: number;
  input?: { name: string; value: unknown }[];
  output: { name: string; value: unknown }[];
  type: CallbackType;
}) => FRCallback;

type MiddlewareFn = (...args: unknown[]) => unknown;

type TokenStoreGetFn = (key: string) => Promise<{
  accessToken: string;
  idToken?: string;
  refreshToken?: string;
  tokenExpiry?: number;
}>;
type TokenStoreSetFn = (key: string) => Promise<void>;
type TokenStoreRemoveFn = (key: string) => Promise<void>;

const isFunction = (v: unknown): boolean => typeof v === 'function';

/**
 * Configure underlying SDK
 */
const configSchema = z
  .object({
    callbackFactory: z.custom<CallbackFactoryFn>(isFunction).optional(),
    clientId: z.string().optional(),
    logLevel: z
      .union([
        z.literal('none'),
        z.literal('error'),
        z.literal('warn'),
        z.literal('info'),
        z.literal('debug'),
      ])
      .optional(),
    middleware: z.array(z.custom<MiddlewareFn>(isFunction)).optional(),
    realmPath: z.string(),
    redirectUri: z.string().optional(),
    scope: z.string().optional(),
    serverConfig: z
      .object({
        baseUrl: z
          .string({
            error: (issue) =>
              issue.input === undefined
                ? 'Setting the `serverConfig.baseUrl` is required (this is generated by the Zod library).'
                : '`serverConfig.baseUrl` is a required URL string (this is generated by the Zod library).',
          })
          .url({
            message:
              '`serverConfig.baseUrl` must be a full URL (this is generated by the Zod library).',
          }),
        paths: z
          .object({
            authenticate: z.string().optional(),
            authorize: z.string().optional(),
            accessToken: z.string().optional(),
            endSession: z.string().optional(),
            userInfo: z.string().optional(),
            revoke: z.string().optional(),
            sessions: z.string().optional(),
          })
          .strict()
          .optional(),
        timeout: z
          .number({
            error: () =>
              '`serverConfig.timeout` is a required number and in milliseconds (this is generated by the Zod library).',
          })
          .optional(),
      })
      .strict(),
    support: z.union([z.literal('legacy'), z.literal('modern')]).optional(),
    tokenStore: z
      .union([
        z
          .object({
            get: z.custom<TokenStoreGetFn>(isFunction),
            set: z.custom<TokenStoreSetFn>(isFunction),
            remove: z.custom<TokenStoreRemoveFn>(isFunction),
          })
          .strict(),
        z.literal('sessionStorage'),
        z.literal('localStorage'),
      ])
      .optional(),
    tree: z.string().optional(),
    type: z.string().optional(),
    oauthThreshold: z.number().optional(),
  })
  .strict();
export const partialConfigSchema = configSchema.partial();

/**
 * @function - Sets the configuration for the SDK
 * @param {object} config - The configuration object
 * @returns {void}
 */
export default function (config: z.infer<typeof partialConfigSchema>) {
  configSchema.parse(config);
  Config.set(config);
}
