/**
 * Copyright © 2025 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 * This file post-processes the types generated by svelte-package
 * to remove Svelte-specific declarations that shouldn't be exposed
 * to framework-agnostic consumers, and rewrites internal alias paths
 * ($core, $journey, $components, $locales) to relative paths so npm
 * consumers can resolve them.
 *
 * After copyTypes.mjs copies core type files into dist/core/, this
 * script also rewrites alias paths inside those copied files, using
 * depth-aware relative paths so imports resolve correctly from their
 * new locations.
 *
 * Note: Svelte 5 no longer generates the `declare module '*.svelte'`
 * block, so this script now gracefully handles its absence.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { dirname, join, relative } from 'path';
import { fileURLToPath } from 'url';

const declareModuleSection = `declare module '*.svelte' {
    export { SvelteComponentDev as default } from 'svelte/internal';
}
`;

const importMetaPath = fileURLToPath(import.meta.url);
const importMetaDirectoryPath = dirname(importMetaPath);

const distDir = join(importMetaDirectoryPath, '../', 'dist');
const index = join(distDir, 'index.d.ts');
const types = join(distDir, 'types.d.ts');
const interfaces = join(distDir, 'interfaces.d.ts');

let cleanedCount = 0;

/**
 * Alias replacements for widget type files in dist/.
 * Core types are namespaced under dist/core/ to avoid collisions
 * (e.g., core/interfaces.d.ts vs widget's own interfaces.d.ts).
 */
const widgetAliasReplacements = [
  { pattern: /\$core\//g, replacement: './core/' },
  { pattern: /\$journey\//g, replacement: './core/journey/' },
  { pattern: /\$components\//g, replacement: './core/components/' },
  { pattern: /\$locales\//g, replacement: './core/locales/' },
];

/**
 * Attempts to clean Svelte-specific declarations and alias paths from a type file.
 * @param {string} filePath - Path to the type file
 * @returns {boolean} - Whether the file was modified
 */
function cleanTypeFile(filePath) {
  if (!existsSync(filePath)) {
    console.log(`⚠ Skipped ${filePath} (not found)`);
    return false;
  }

  let contents = String(readFileSync(filePath));
  let modified = false;

  // Remove Svelte declare module section if present
  const declareModuleIdx = contents.indexOf(declareModuleSection);
  if (declareModuleIdx !== -1) {
    contents = contents.replace(declareModuleSection, '');
    console.log(`✓ ${filePath} - removed Svelte declare module section`);
    modified = true;
  } else {
    console.log(`✓ ${filePath} - no Svelte declare module section found (OK)`);
  }

  // Rewrite alias paths to relative paths pointing into dist/core/
  for (const { pattern, replacement } of widgetAliasReplacements) {
    if (pattern.test(contents)) {
      pattern.lastIndex = 0;
      contents = contents.replace(pattern, replacement);
      console.log(`✓ ${filePath} - rewrote alias paths: ${pattern.source} → ${replacement}`);
      modified = true;
    }
  }

  if (modified) {
    writeFileSync(filePath, contents);
  }

  return modified;
}

// --- Phase 1: Clean widget type files in dist/ ---

cleanedCount += cleanTypeFile(index) ? 1 : 0;
cleanedCount += cleanTypeFile(types) ? 1 : 0;
cleanedCount += cleanTypeFile(interfaces) ? 1 : 0;

console.log(`\nWidget type cleaning complete: ${cleanedCount} files modified`);

// --- Phase 2: Rewrite aliases in copied core type files under dist/core/ ---

const coreDistDir = join(distDir, 'core');

/**
 * Recursively finds all .d.ts files under a directory.
 * @param {string} dir - Directory to search
 * @returns {string[]} - Array of absolute file paths
 */
function findDtsFiles(dir) {
  const results = [];
  if (!existsSync(dir)) return results;

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      results.push(...findDtsFiles(fullPath));
    } else if (entry.endsWith('.d.ts')) {
      results.push(fullPath);
    }
  }
  return results;
}

/**
 * Computes the relative prefix from a file's location back to dist/core/.
 * E.g., dist/core/oauth/oauth.store.d.ts → '../'
 *       dist/core/interfaces.d.ts → './'
 */
function computeCoreRelativePrefix(filePath) {
  const fileDir = dirname(filePath);
  const rel = relative(fileDir, coreDistDir);
  if (rel === '') return './';
  return rel + '/';
}

if (existsSync(coreDistDir)) {
  const coreDtsFiles = findDtsFiles(coreDistDir);
  let coreCleanedCount = 0;

  for (const filePath of coreDtsFiles) {
    let contents = String(readFileSync(filePath));
    let modified = false;
    const corePrefix = computeCoreRelativePrefix(filePath);

    // $core/ → relative path to dist/core/
    const corePattern = /\$core\//g;
    if (corePattern.test(contents)) {
      corePattern.lastIndex = 0;
      contents = contents.replace(corePattern, corePrefix);
      console.log(`✓ ${filePath} - rewrote $core/ → ${corePrefix}`);
      modified = true;
    }

    // $journey/ → relative path to dist/core/journey/
    const journeyPattern = /\$journey\//g;
    if (journeyPattern.test(contents)) {
      journeyPattern.lastIndex = 0;
      const journeyPrefix = corePrefix + 'journey/';
      contents = contents.replace(journeyPattern, journeyPrefix);
      console.log(`✓ ${filePath} - rewrote $journey/ → ${journeyPrefix}`);
      modified = true;
    }

    // $components/ → relative path to dist/core/components/
    const componentsPattern = /\$components\//g;
    if (componentsPattern.test(contents)) {
      componentsPattern.lastIndex = 0;
      const componentsPrefix = corePrefix + 'components/';
      contents = contents.replace(componentsPattern, componentsPrefix);
      console.log(`✓ ${filePath} - rewrote $components/ → ${componentsPrefix}`);
      modified = true;
    }

    // $locales/ → relative path to dist/core/locales/
    const localesPattern = /\$locales\//g;
    if (localesPattern.test(contents)) {
      localesPattern.lastIndex = 0;
      const localesPrefix = corePrefix + 'locales/';
      contents = contents.replace(localesPattern, localesPrefix);
      console.log(`✓ ${filePath} - rewrote $locales/ → ${localesPrefix}`);
      modified = true;
    }

    if (modified) {
      writeFileSync(filePath, contents);
      coreCleanedCount++;
    }
  }

  console.log(`Core type cleaning complete: ${coreCleanedCount} files modified`);
} else {
  console.log('⚠ No dist/core/ directory found — skipping core type cleaning');
}
