// AUTO-GENERATED by ping-law CLI — do not edit manually
// Re-run `ping-law scan` to regenerate

export const customStages = {} as Record<string, unknown>;

export const customCallbacks = {} as Record<string, unknown>;
