import { CallbackType } from "@forgerock/javascript-sdk";

export default {
    "authId": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6ImVtYmVkZWRsb2dpbiIsIm90ayI6ImdvNmNwcTQ5YXJyajM2MnM0MWg0ZzVxOHJ0IiwiYXV0aEluZGV4VHlwZSI6InNlcnZpY2UiLCJyZWFsbSI6Ii9hbHBoYSIsInNlc3Npb25JZCI6IipBQUpUU1FBQ01ESUFCSFI1Y0dVQUNFcFhWRjlCVlZSSUFBSlRNUUFDTURFLipleUowZVhBaU9pSktWMVFpTENKamRIa2lPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LlpYbEtNR1ZZUVdsUGFVcExWakZSYVV4RFNteGliVTFwVDJsS1FrMVVTVFJSTUVwRVRGVm9WRTFxVlRKSmFYZHBXVmQ0YmtscWIybGFSMng1U1c0d0xpNWtZbkpLZW1oWU5rbDRUamQxUW05b1lteHdabTUzTGt4Zk0ydEhMVmQwV1RGMU0zbFpNV1owZDNvdGQweFpOWFJ4U2xabFVuQnNOa2wyZWxocFFsQTRhblJrVms1cVR6UTVRV014V0ROb1JGSmlVMUJzYnpGTVRtMXdkMDh0U0hsdlVVVllMVEI0Y25WWVNWQm5WVVpITTBrdFRESnRUV3QyZW1OMGFURnZVRmxuYlhFME4xaDRibFZXVTA4NVYwbHJaRFpaTjIxaFZtUnFTbmhIYUZGcU9HeEpUWEEzT0VGcWRqSmtWRkkxYmtwc1ptOHRVRXh4ZG1KWFFtVkZTVlZ6ZG5JNWVWcFFRbGxMVW0xV2NXZExiVU53WVZSdE0wVnJZWE15V25oc1NscDRWRlpYUVZoMExVMWZObXhTYTJjd05rUmtRV0oyUmtveFZFZG9ia0paY0dFelFYVk5Va2hLUldaa1JucFBiSEo2UWxSTWFIZGtaM0JPYlZoUU5WQkNWMFJvYkRkZlRrUjBhMEZmZUhwdFdXUmpkek5RTkZKaVpYcG9SVlJ5TkhWMmNWVnFORUZWWVhkUVVXaHFNbVZZVFdRNFRtZGphbU5TT1cxcGEzTm5SSE01T1U1T2NsbExTbVZuTkdodWJFaHpOVE5KWVU1cmR6WnpSemxLWmtSUVYydDJhVll0TjFVNE5UbHROSE5tVTNGNmNsZHdjbXBWYm1WMVlWQjBiVVZTUkRGMWVtRlRNVnBIY1hwU2EwaGZTV3BEYTNKdWIyZGZSM3BwWjNFMlFtWmFNMUJ0ZWswelZWUkZUVTVCTjJWVFR6ZHpOa0puV0MxSldFY3lUbmhyWldOUWFYcG9XRzVXUkdoVFpqSkhZMkY2Y2twSmJGSkhkVWRFU0VGdWMyUjNMVUoyUm01SGFteG1Tamd3Y0Y5Q2RsTnVXa0V6ZVZrM1YxWjJhMEpZYUVOZmVuWTJUamxEVUhrdE1XZERaRkJwV1hWRlJFdGlTRE14TUc4NWFHZ3RVRFpDV25aaE0xVkpMVzlOVG1SWVp6a3lWbFZ5UTA1VmEwcFdNbkJpTFRCd1dXbHlkMFZ0YWpCZlRtRXdiRE0xYjE5S2IxYzNWVTVIWmxwc1dXNWxSR3N1YzA5V2FFb3ROalZWVVZkUlVsQjNhVFpOVmtGVVp3LkpVYlNrNENzdUlmWERaNFVDMGhaNXVhajZJWkhUR3BpN2dxOS0wUGh3aTgiLCJleHAiOjE2NjM3MTA0MjksImlhdCI6MTY2MzcxMDEyOX0.mVqcNFr0V5HC3-ZsO1Jjbr44dQ5DtrpNfQ0nMJ2vGOQ",
    "callbacks": [
        {
            "type": CallbackType.SuspendedTextOutputCallback,
            "output": [
                {
                    "name": "message",
                    "value": "An email has been sent to the address you entered. Click the link in that email to proceed."
                },
                {
                    "name": "messageType",
                    "value": "0"
                }
            ]
        }
    ]
}
