export default {
  authId:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRoSW5kZXhWYWx1ZSI6IkxvZ2luV2l0aENvbmZpcm1hdGlvbkFuZENob2ljZSIsIm90ayI6ImVwdnRvZXVmMjNpbW5xM2hqMG5pcGltazJnIiwiYXV0aEluZGV4VHlwZSI6InNlcnZpY2UiLCJyZWFsbSI6Ii9hbHBoYSIsInNlc3Npb25JZCI6IipBQUpUU1FBQ01ESUFCSFI1Y0dVQUNFcFhWRjlCVlZSSUFBSlRNUUFDTURFLipleUowZVhBaU9pSktWMVFpTENKamRIa2lPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LlpYbEtNR1ZZUVdsUGFVcExWakZSYVV4RFNteGliVTFwVDJsS1FrMVVTVFJSTUVwRVRGVm9WRTFxVlRKSmFYZHBXVmQ0YmtscWIybGFSMng1U1c0d0xpNTNUbVZDUlZsVU1XaENSRlZYWHpsVFJYWXdXRFpCTGtwdFpqUnNXa1ZyV2xZM1VrZHFXa1ZKUWt4c2ExVllhblpWVjJscGJFZE9Sa3cxU0RCdGRtVm9lblJJZEhwcVlYWXdSWFo1V1VKTGFrNWhWblZLVVV0NWJVbHZVakZGWldOeVJWRkdXR3czWnpkVVYweHRNVUpvVlRBeE5HTXRRVEpzZEdaWVJXcFdkRU5XZVZkWU5uVnJUSFl0ZVRSUmNtSk9kbXhVZGtOV2VXcHBOMmRHTFRObFRrRllOV2RyVTNGZlltVTVSMDUwWkRBMVpWOURabU5SY1UweWQzbHdhVlo1TUVFdGNXSkhNRnBVUkU1clFVdFBlalZITUdwUE5sbzBiUzAyYWtFM1lVaHFaM2RIWkhCdVFrdGtVMkV6ZVhwbVJFdGtNblF6YTNoMWRVdGpia0psYUZaTFUxTkZkRGhoTUc1d2FFWlRhM1poU1ZSNFlWOXVURGN5ZFVwelFsbHpkRFZmYzNST1VUTmtkRWg1UkZwZlZDMTBiMFEzUWxKdWNrUlhTVFZUUTJsWlVqaFJZVFZyWW1aT2FEUnBZbkUwUTBsa2RrcGZOM3BvU0VKd01IRk9SMHR6Um05YU1FdG9WVGc1YkZkT1FVcGZWVzU2VWtKUlRVa3dWV3hrYW5GVWJ6RmZjREExYkU5bFRsTmZhRkU0VlRoaWNqRXdjV0V4VGpoQmVVWlVORlF4U0c0eVZqWkJObFJWYjFsMU5IbE9NVk5aYlRKVlFVSlVhRGRFYkVGd1pWQm1kVGhuY25ONk5rWlZjRTFGZWtkVmNTMUhhMTlFZFU1blFUbE5MVGRJYUZreVpUZG5UMFJ2T0hoRmNFZHRRbVUyZWxGZkxXZEpkbnBWWVRGWmFDMHhRa1E0VGxrMlpsVkhhMkZKZEZSWmN6Rm5Va2t3UWpsWGVGZHFhMHgyVlZSRGJIZFNhbmhMVkcxMVFWZGZhbVZ5WDJZMFpVOTNTbEpGZGpVMldtTjRkV2hXZGtWMGFsTmlXREZTYlc0dGRrWTRSMjVxVTJjMVMxZ3Rka2gzVmpOUlpHVnJYMjFQV1cxNmRIcEViMU16Y25rMlVFTkphUzB4YTBwSlNGOUZlaTB0U1c1VVFXMU1SMk5aTURSR1EyMVpXblU0V0MxQldHWXRXRXgyYUhaVlIyWm5VVmhuTlhWcFQyZHFWMjFPZFZOTFEydGhNWEY0UTNKa1NubDVhazVqYm1sSGJIRmplWFp6V2pORWN6SkpkRE55TFVwT1dWOXZlVTgyUjAweFEwZEJZV0kwVFdkNk56QklXREk1Vm1KWmNsVXRMVEJrUzJaVE9YUklVVjlmY0d0TWVGcHNaeTFQTFdzMWRHRm5RMHBZTjIxclR6bFhZV0ozYVdsR01FcFVZWEpsVTFKSFJ6VlBRWEJ5T1Y5Tk1sZDVNVFJUVEVWeVJVRkRSbkp3UldKWmRVdHNlazFSTlU1MFVEUm1XR1ZhTUdvdGJVRjZjMGg0VTBkbUxXNUNNV1ozTTFCUFRuRnhNMUIyWTJaRFZXTnRZMVkzYWsxR2RHcHRiWGhHZUdaTU1UaHFaMlp5U0ROU05FNXRiekpCVGxCTFRXRnhkMWRwY1ZoMVlqa3hjbTR3VVU1RlIybHNOVzFqWDBndGRITnZTSGRqVFZjd1RtNUtSMjUyWDI5RE9WZDRXVVZGVHkxeGNYZ3hWV2d0TVdvNVQzVldPWEZaVTNaUWVFNWpTRTQxTlRSSFRVNXZMVFJTUW5wVldrdG5RV3hqT0VaeFQzWkdUbTF6ZFdaU2VIUTBSbm95YUVWMVlVNUROWEU0ZGs1WldFSkJNR2xRYVhwRmIzcG9WVlYwZUZSMlRWSnRhekZKUVhwQkxsQldRM3BEWjNwZmNreGhUbFkxYW5nNFQzVlNiSGMuSmM1VUl6Tl9ORVRwSkoxcWNtNjBpWjhreWYzZ2YtRGYxUThrZk5ldnI5QSIsImV4cCI6MTY2NTQzOTE3NCwiaWF0IjoxNjY1NDM4ODc0fQ.HOVo238jdHSY0gjYCbq4mn53LlC2W1QeShabgD7t-nU',
  callbacks: [
    {
      type: 'PollingWaitCallback',
      output: [
        { name: 'waitTime', value: '2000' },
        { name: 'message', value: 'Please wait while we process your request.' },
      ],
    },
    {
      type: 'ConfirmationCallback',
      output: [
        { name: 'prompt', value: '' },
        { name: 'messageType', value: 0 },
        { name: 'options', value: ['Cancel out of flow.'] },
        { name: 'optionType', value: -1 },
        { name: 'defaultOption', value: 0 },
      ],
      input: [{ name: 'IDToken2', value: 100 }],
    },
  ],
};

export const docsExample = {
  type: 'PollingWaitCallback',
  output: [
    {
      name: 'waitTime',
      value: '8000',
    },
    {
      name: 'message',
      value: 'Waiting for response...',
    },
  ],
};
