/**
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 **/

import { protect } from '@forgerock/protect';
import { get, writable } from 'svelte/store';
import { z } from 'zod';

import type {
  Protect,
  ProtectConfig as SdkProtectConfig,
  SignalsInitializationOptions,
} from '@forgerock/protect/types';
import type { Readable } from 'svelte/store';

/**
 * The legacy `@forgerock/ping-protect` `PIProtect` export was a singleton: one callback could
 * `start(config)` and a later callback could `getData()` against the same initialized SDK.
 *
 * The new `@forgerock/protect` `protect(config)` factory returns a *stateful protectClient* whose
 * `getData`/`pauseBehavioralData`/`resumeBehavioralData` only work after `start()` has run on
 * that same protectClient. To preserve the cross-callback behavior the widget relies on, we hold a
 * single shared protectClient in a Svelte store here and reuse it across all consumers (both Ping
 * Protect callbacks and the public `protect` widget API).
 */

/**
 * Schema for the consumer-facing public API shape.
 * Validates the `ProtectConfig` shape — requires `envId` and typed fields.
 * `.strict()` rejects unrecognized keys when the input is parsed as `ProtectConfig`.
 */
export const protectConfigSchema = z
  .object({
    envId: z.string({
      error: (issue) =>
        issue.input === undefined
          ? 'Setting `envId` is required (this is generated by the Zod library).'
          : '`envId` must be a string (this is generated by the Zod library).',
    }),
    waitForWindowLoad: z.boolean().optional(),
    hubUrl: z.string().optional(),
    disableHub: z.boolean().optional(),
    deviceAttributesToIgnore: z.array(z.string()).optional(),
    behavioralDataCollection: z.boolean().optional(),
    disableTags: z.boolean().optional(),
    externalIdentifiers: z.record(z.string(), z.string()).optional(),
    universalDeviceIdentification: z.boolean().optional(),
    agentIdentification: z.boolean().optional(),
    agentTimeout: z.number().optional(),
    agentPort: z.number().optional(),
    consoleLogEnabled: z.boolean().optional(),
  })
  .strict();

/**
 * Schema for callback-provided PingOne Signals initialization options.
 * The Ping JS SDK defines this as an arbitrary string key-value map.
 */
export const signalsInitializationOptionsSchema = z.record(z.string(), z.string());

/**
 * Schema for all supported Protect start config shapes.
 * This replaces the previous manual `'envId' in config` branching.
 */
export const protectStartConfigSchema = z.union([
  protectConfigSchema,
  signalsInitializationOptionsSchema,
]);

export type ProtectConfig = z.infer<typeof protectConfigSchema>;
export type ProtectStartConfig = z.infer<typeof protectStartConfigSchema>;

export interface ProtectStore extends Readable<Protect | null> {
  start: (
    config: ProtectConfig | SignalsInitializationOptions,
  ) => Promise<void | { error: string }>;
  getData: () => Promise<string | { error: string }>;
  pauseBehavioralData: () => void | { error: string };
  resumeBehavioralData: () => void | { error: string };
}

const protectClientStore = writable<Protect | null>(null);

/**
 * @function start - Creates (or recreates) the shared Protect client and starts it.
 * @throws {z.ZodError} If config does not match any supported Protect start config shape.
 * @returns {Promise<void | { error: string }>}
 */
function start(config: ProtectConfig | SignalsInitializationOptions) {
  const safeConfig = protectStartConfigSchema.parse(config) as
    | SdkProtectConfig
    | SignalsInitializationOptions;
  const protectClient = protect(safeConfig);
  protectClientStore.set(protectClient);
  return protectClient.start();
}

/**
 * @function getData - Returns device data from the shared Protect client.
 * @returns {Promise<string | { error: string }>}
 */
function getData() {
  const protectClient = get(protectClientStore);
  if (!protectClient) {
    return Promise.resolve({ error: 'PingOne Signals SDK is not initialized' });
  }
  return protectClient.getData();
}

/**
 * @function pauseBehavioralData - Pauses behavioral data collection on the shared client.
 * @returns {void | { error: string }}
 */
function pauseBehavioralData() {
  const protectClient = get(protectClientStore);
  if (!protectClient) {
    return { error: 'PingOne Signals SDK is not initialized' };
  }
  return protectClient.pauseBehavioralData();
}

/**
 * @function resumeBehavioralData - Resumes behavioral data collection on the shared client.
 * @returns {void | { error: string }}
 */
function resumeBehavioralData() {
  const protectClient = get(protectClientStore);
  if (!protectClient) {
    return { error: 'PingOne Signals SDK is not initialized' };
  }
  return protectClient.resumeBehavioralData();
}

export const protectStore: ProtectStore = {
  subscribe: protectClientStore.subscribe,
  start,
  getData,
  pauseBehavioralData,
  resumeBehavioralData,
};
