/**
 * Vite plugin that scans /user/stage and /user/callback for custom Svelte
 * components and generates core/journey/_utilities/custom-registry.ts.
 *
 * Runs on buildStart (dev + prod) and watches the /user directory for
 * changes during dev to regenerate the registry automatically.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

interface ComponentMetadata {
  readonly type: 'callback' | 'stage';
  readonly name: string;
}

interface DiscoveredComponent extends ComponentMetadata {
  readonly relativePath: string;
}

function parseComponentMetadata(source: string): ComponentMetadata | null {
  const match = source.match(/<!--\s*@component\s+Type:\s*(callback|stage)\s+Name:\s*(\w+)\s*-->/s);
  if (!match) return null;
  return { type: match[1] as 'callback' | 'stage', name: match[2] };
}

function scanUserDirectory(userDir: string): DiscoveredComponent[] {
  const components: DiscoveredComponent[] = [];

  for (const componentType of ['stage', 'callback'] as const) {
    const typeDir = path.join(userDir, componentType);
    if (!fs.existsSync(typeDir)) continue;

    for (const entry of fs.readdirSync(typeDir)) {
      const componentFile = path.join(typeDir, entry, 'component.svelte');
      if (!fs.existsSync(componentFile)) continue;

      const source = fs.readFileSync(componentFile, 'utf-8');
      const metadata = parseComponentMetadata(source);
      if (!metadata) continue;

      components.push({
        ...metadata,
        relativePath: `${componentType}/${entry}/component.svelte`,
      });
    }
  }

  return components;
}

function generateRegistrySource(components: DiscoveredComponent[]): string {
  const stages = components.filter((c) => c.type === 'stage');
  const callbacks = components.filter((c) => c.type === 'callback');

  const lines: string[] = [
    '// AUTO-GENERATED by vite-plugin-custom-registry — do not edit manually',
    '',
  ];

  for (const component of [...stages, ...callbacks]) {
    lines.push(`import ${component.name} from "$user/${component.relativePath}";`);
  }

  if (components.length > 0) lines.push('');

  if (stages.length === 0) {
    lines.push('export const customStages = {} as Record<string, unknown>;');
  } else {
    lines.push('export const customStages = {');
    for (const stage of stages) {
      lines.push(`  "${stage.name}": ${stage.name},`);
    }
    lines.push('} as Record<string, unknown>;');
  }

  lines.push('');

  if (callbacks.length === 0) {
    lines.push('export const customCallbacks = {} as Record<string, unknown>;');
  } else {
    lines.push('export const customCallbacks = {');
    for (const cb of callbacks) {
      lines.push(`  "${cb.name}": ${cb.name},`);
    }
    lines.push('} as Record<string, unknown>;');
  }

  lines.push('');
  return lines.join('\n');
}

function writeRegistryIfChanged(userDir: string, registryPath: string): void {
  const components = fs.existsSync(userDir) ? scanUserDirectory(userDir) : [];
  const newSource = generateRegistrySource(components);

  // Only write if content actually changed — avoids unnecessary HMR triggers
  if (fs.existsSync(registryPath)) {
    const existing = fs.readFileSync(registryPath, 'utf-8');
    if (existing === newSource) return;
  }

  fs.mkdirSync(path.dirname(registryPath), { recursive: true });
  fs.writeFileSync(registryPath, newSource);
}

export interface CustomRegistryPluginOptions {
  /** Absolute path to the project root (where /user lives) */
  root: string;
}

export function customRegistryPlugin(options: CustomRegistryPluginOptions): Plugin {
  const userDir = path.join(options.root, 'user');
  const registryPath = path.join(options.root, 'core/journey/_utilities/custom-registry.ts');

  return {
    name: 'custom-registry',

    buildStart() {
      writeRegistryIfChanged(userDir, registryPath);
    },

    configureServer(server) {
      // Watch the /user directory for changes during dev
      server.watcher.add(userDir);
      server.watcher.on('all', (event, filePath) => {
        if (!filePath.startsWith(userDir)) return;
        if (!filePath.endsWith('.svelte')) return;

        writeRegistryIfChanged(userDir, registryPath);
      });
    },
  };
}
